### ISSUE TITLE
Desarrollar el primer diseño de la página web

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#10]
Diseñar una página de inicio de que contenga el logo de Unillanos, el logo de FCBI y algo alusivo ya sea a los objetos NGC o a la astronomía. El fondo puede ser un fondo de astronomía o algo por el estilo...

La parte de diseño es un lugar donde se deja volar la creatividad de un artista, así que cualquier idea será bien recibida.

### Sci-Hub
![image](https://user-images.githubusercontent.com/15129146/36607832-e4ca21f6-1895-11e8-838b-4ff27e9911d8.png)

**Comment by hamiltonsalazar** [comment]
Esta tarea se llena de nuevo "To do", es necesario primero tener un Mockup de ella #67

**Comment by hamiltonsalazar** [comment]
Se cierra por tiempo.
