### ISSUE TITLE
Recolectar información sobre las librerías que trabajan Machine Learning. Parte 1

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#100]
Hacer una investigación más amplia acerca del tema. @andres-linares sugiere TensorFlow como la más conocida en Python, profundizar en esta y buscar otras alternativas.

**Comment by jmencisom** [comment]
Otras sugerencias:

http://scikit-learn.org/stable/
http://www.nltk.org/
http://torch.ch/

**Comment by andres-linares** [comment]
Breve descripción sobre las cinco principales librerías python que trabajan procesamiento de lenguaje natural (inglés):
https://elitedatascience.com/python-nlp-libraries

**Comment by andres-linares** [comment]
Las librerías encontradas fueron Scikitlearn, NLTK y Tensorflow. Solo se implementan las dos primeras.
