### ISSUE TITLE
Identificar la manera en la que se llevará el texto a múltiples idiomas. Parte 1

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#103]
Buscar las técnicas posibles para que el texto del artículo se traduzca a diferentes idiomas, teniendo en cuenta posibles cambios que pueden haber dentro de las plantillas en cada idioma.

**Comment by andreveca** [comment]
No se va a realizar por ahora. Fuera del alcance actual
@jmencisom

**Comment by hamiltonsalazar** [comment]
Se cierra por tiempo.
