### ISSUE TITLE
Plantear un modelo de organización de archivos

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#11]
¿Tener todos los archivos en una sola carpeta o directorio?

Tener un modelo de organización ayudaría a tener un mayor control en el proyecto. Separar archivos de código de otros archivos, front-end de back-end, etc...

**Comment by andreveca** [comment]
@andres-linares los resultados los subo a una Wiki o por aquí?

**Comment by andres-linares** [comment]
Acá puede ser.

**Comment by andreveca** [comment]
Indagando en la red, pude encontrar que hay tres directorios que cada proyecto debe tener, los cuales son:

- Un directorio **Docs** el cual contendrá la documentación del proyecto.
- Un directorio con el **nombre del proyecto**, que almacena el paquete de Python
- Un directorio **Test** en uno de los dos lugares siguientes:
    *En el directorio del paquete que contiene el código de prueba y los recursos
    *Como un directorio independiente de nivel superior

Para tener una idea mejor de como organizarlos Jeff Knupp nos muestra una idea simplificada del diseño de uno de sus proyectos
![image](https://user-images.githubusercontent.com/36459536/37070721-e82f8db4-2186-11e8-87c9-a00594f6a48d.png)

Como se puede ver hay algunos archivos de nivel superior, un directorio _docs_ ( **generated** es un directorio vacío donde sphinx colocara la documentación generada), un directorio **sandman**, y un directorio **test** dentro de **sandman**, cabe aclarar que sadman es el nombre del proyecto.


_Fuente:_
http://www.patricksoftwareblog.com/structure-of-a-python-project/
https://jeffknupp.com/blog/2013/08/16/open-sourcing-a-python-project-the-right-way/
