### ISSUE TITLE
Contactar astrónomo para averiguar  el sueldo por una hora de consultoría.

### ISSUE THREAD

**Issue by fraroca97** [jmencisom/wikastro#13]
Es necesario para poder llevar a cabo la planeación del presupuesto.

**Comment by jmencisom** [comment]
¿En qué estado se encuentra esta tarea?

**Comment by hamiltonsalazar** [comment]
Actualmente esta tarea se encuentra en espera, debido a que el último lugar donde se comunicó el compañero @luiscarlosmartg le solicitaron un correo donde le enviarían la información y no ha llegado.

@wildimarnieto por favor colaborar en la consulta en diferentes lugares de los ya consultados por Luis, para una pronta solución a ésta.

**Comment by andreveca** [comment]
@luiscarlosmartg aun no le responden al correo? 
@wildimarnieto ha conseguido alguna información al respecto?

**Comment by luiscarlosmartg** [comment]
ya he mandado un tercer correo hace tres dias desde una cuenta diferente y no he tenido respuesta, lo cual he manifestado en clase,  creo que ya no debemos perder mas tiempo en esto y sugiero que calculemos el precio hora del astronomo a partir de alguna formula, encontre esta pagina de la cual nos podiamos guiar http://www.emprendedores.es/gestion/como-calcular-tu-precio-hora, estare atento a la aprobación

**Comment by hamiltonsalazar** [comment]
Se toma en cuenta la sugerencia de @luiscarlosmartg para un estimado del astrónomo, debido a que no se consigue respuesta alguna a los correos enviados ni llamadas de ninguno de los responsables.
