### ISSUE TITLE
Llevar a cabo la primera reunión de calidad

### ISSUE THREAD

**Issue by georgebaron** [jmencisom/wikastro#14]
Jhonatan mejia y lina león por favor comunicarse para el análisis a realizar del proyecto y definir un día en concreto para las reuniones

**Comment by fraroca97** [comment]
@LinaMejia  Pertenece actualmente al equipo de desarrollo (según lo establecido en la wiki de "Metodología de desarrollo de software"), su reemplazo en el puesto es @danielmrno

**Comment by hamiltonsalazar** [comment]
@georgebaron como líder del equipo si  ve necesario o pertinente la reunión de su equipo de trabajo, requiero por favor un acta de cada reunión donde conste los días y la hora en que se reúnen, personas asistentes a cada una de éstas reuniones y temas tratados en ellas.

**Comment by hamiltonsalazar** [comment]
No se lleva a cabo.
