### ISSUE TITLE
Promediar número de artículos científicos por objeto NGC

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#144]
¿Cuál el el número promedio de artículos científicos por objecto NGC?

¿Posiblemente @andres-linares tiene alguna pista?

**Comment by andres-linares** [comment]
Se puede hacer de distintas maneras. Las listaré de menos detallado a más detallado y de más rápido a más lento:
- Contar el número de artículos científicos basandonos en el número de referencias en simbad.
- Contar el número de artículos científicos basandonos en el número de referencias en simbad que dan la dirección a una página web.
- Contar el número de artículos científicos basandonos en el número de referencias que permiten acceder a la página web de los artículos.
- Contar el número de artículos científicos basandonos en el número de referencias que permiten acceder al artículo en pdf.

También se podría sacar estadísticas de cada una de las cuatro cláusulas anteriores.

De cualquier forma que sea escogida, yo me puedo encargar de desarrollar un algoritmo que obtenga las estadísticas y mostrarlas en una gráfica usando la librería pyplot o seaborn. (El problema vendrá con las múltiples peticiones desde una misma ip)

**Comment by andres-linares** [comment]
Acabo de crear un código para obtener el promedio de artículos científicos por objeto NGC y mi recomendación es llegar solamente hasta la segunda cláusula puesto que ir más allá eleva el tiempo de una manera considerable.

Obtuve las siguientes estadísticas para los **primeros 100 objetos NGC** con una conexión a internet de 10 mbps:
- Promedio de artículos (cláusula 1) por objeto NGC: **52.860**
- Promedio de artículos (cláusula 2) por objeto NGC: **42.290**
- Promedio de tiempo para obtener los artículos (cláusula 1) por objeto NGC: **1.122 _seg_**
- Promedio de tiempo para obtener los artículos (cláusula 2) por objeto NGC: **31.623 _seg_**

En base a lo anterior... Para obtener las estadísticas de los 7840 objetos NGC, se tomará un tiempo de:
- (1.122 + 31.623) seg * 7840 = 32.745 seg * 7840 = 256,729.8 seg = 4,278.68 min = 71.31 horas = 2.97 días.


### Gráficas:
![imagen](https://user-images.githubusercontent.com/15129146/38775751-591c1218-404f-11e8-94a5-94c39cbb9d57.png)

**Comment by andres-linares** [comment]
El algoritmo lo mejoré y ahora es capaz de recuperarse de errores como la pérdida de conexión a internet y los cierres accidentales (o intencionales). De tal manera que si el internet se va, el programa se queda esperando hasta que llega el internet y vuelve a iniciar la busqueda de referencias del último objeto NGC; En el caso de un cierre accidental o intencional, la información se va guardando en 4 archivos binarios y una vez se vuelve a abrir el programa, se carga la información y se comienza a buscar desde el último objeto NGC.

Cada vez que se abre el programa se muestran las estadísticas y una vez cerrada la ventana donde aparecen los gráficos, se reinicia la búsqueda.
He hecho búsquedas hasta el objeto NGC 150. Me detengo en este punto para que el encargado retome la labor. Las estadísticas hasta el momento son:
![imagen](https://user-images.githubusercontent.com/15129146/38781603-45c5ee7e-40ad-11e8-91be-3f4d5383d1c9.png)


El programa está alojado en la rama pruebasObjetos y en esta rama el archivo requirements.txt contiene las librerías esenciales.

**Comment by hamiltonsalazar** [comment]
La tarea se cierra por tiempo y se cuenta a como realizada a @andres-linares debido a su labor de investigación.
