### ISSUE TITLE
Calcular porcentaje de articulos NGC faltantes

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#145]
Calcular porcentaje de articulos NGC faltantes en Wikipedia inglés

[# artículos faltantes] / 7840

Gracias!

**Comment by jmencisom** [comment]
Listado de todos los objectos NGC https://en.wikipedia.org/wiki/List_of_NGC_objects

@hamiltonsalazar Necesito este dato lo antes posible. Por favor asignar a quién pueda dar respuesta oportuna.

**Comment by hamiltonsalazar** [comment]
El número de los artículos NGC faltantes en Wikipedia inglés es 6041

**Comment by jmencisom** [comment]
77%
