### ISSUE TITLE
Implementar en el código fuente del proyecto la solución al Issue #86

### ISSUE THREAD

**Issue by fraroca97** [jmencisom/wikastro#148]
Con la página ya conocida y tras el respectivo proceso de análisis, se hace necesario implementar la solución al issue #86 relacionado al descubridor del objeto.

**Comment by LinaMejia** [comment]
descargo el archivo xls desde el código fuente con la librería urllib `quote_page ='http://ngcicproject.org/public_HCNGC/Public_HCNGC.xls'
url_op.urlretrieve(quote_page, "test.xls")`
y luego con la librería xlrd ingreso al archivo y extraigo el valor de la filay columna necesaria
![image](https://user-images.githubusercontent.com/33190990/39688068-9e5a7858-5196-11e8-86e1-ef04cb780f3c.png)
**esto lo trabaje en un archivo aparte así que me quedaría implementarlo en el código del proyecto**

**Comment by LinaMejia** [comment]
En la clase **BasicInfo.py** hice el método `getDiscovererAndYear(self,ngc_num):`.

![image](https://user-images.githubusercontent.com/33190990/39951015-8c105574-554b-11e8-89b3-6e0e4aab6075.png)


y en el método **transformToWikiBox** de  la clase **WikiGeneration.py** agregué estos campos:
![image](https://user-images.githubusercontent.com/33190990/39951115-84a1ee6e-554c-11e8-9603-b4cfeae2483a.png)

el resultado:
![image](https://user-images.githubusercontent.com/33190990/39951146-c68908ee-554c-11e8-984d-5b27c977dafd.png)

dando por cumplida esta tarea.

**Comment by andres-linares** [comment]
El alcance del **issue** actual ha sido cumplido y por lo tanto se da por terminado.

Algunas recomendaciones fueron dadas por el Ingeniero y han de ser cumplidas, por lo tanto es necesario crear un nuevo issue. @fraroca97
