### ISSUE TITLE
Reunion de lideres

### ISSUE THREAD

**Issue by georgebaron** [jmencisom/wikastro#15]
Establecer un día en concreto donde detallemos los avances y problemas, para el seguimiento del proyecto y la buena practica de el 

Andres Linares
Paula Velasquez
George Baron

**Comment by andres-linares** [comment]
## Disponibilidad:
### Total:

-  Lunes: 16:00 - 18:00
- Martes: 14:00 - 16:00
- Miércoles: 08:00 - 12:00
- Jueves: 10:00 - 12:00
- Viernes: 10:00 - 12:00 y 14:00 - 16:00

### Relativa:
- Lunes: 12:00 - 14:00
- Martes: 12:00 - 14:00
- Miércoles: 12:00 - 14:00
- Viernes: 12:00 - 14:00

**Comment by hamiltonsalazar** [comment]
@georgebaron dentro de las metodologías ágiles, una de las pautas habla del puente de comunicación entre los diferentes grupos de trabajo, en éste caso ese soy yo, para llevar a cabo la articulación correcta del proyecto. Para ello adicional ya hay un horario establecido de reuniones con todo el equipo de trabajo.

Y por último a la próxima si va hacer una reunión de líderes sería bueno que el gerente esté presente, en teoría soy el líder principal :V
