### ISSUE TITLE
Usar atributo score para filtrar bibliografía

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#150]
Tomar solo los artículos de acceso abierto con mayor score:

http://simbad.u-strasbg.fr/simbad/sim-id-refs?Ident=%401492560&Name=NGC%20%20%20%20%201

http://simbad.u-strasbg.fr/Pages/data_bibobjinfo.htx

Determinar el valor mínimo de score para aceptar un artículo como fuente de texto "útil".

Muchas gracias.

**Comment by andres-linares** [comment]
Estoy haciendo un programa que obtenga todas las referencias de los 7840 objetos NGC y las guarde en una base de datos (sqlite) la cual está compuesta (hasta el momento) por una sola tabla que consta de los siguientes atributos:
- **bibcode**, tipo texto, llave primaria.
- **url**, tipo texto.
- **score**, tipo entero.
- **NGCs**, tipo texto.

El último campo, contiene los objetos ngc que hacen referencia al artículo separados por una coma.
Por ejemplo:
```python
>>database_name = 'referencias.sqlite'
>>database = sql.connect(database_name)
>>cursor = database.cursor()
>>busqueda = cursor.execute('SELECT * FROM bibcodes')
>>print busqueda.fetchone()

(u'2018A%26A...609A.102R', u'http://simbad.u-strasbg.fr/simbad/sim-ref?bibcode=2018A%26A...609A.102R', 50, u'1,23,160,165,177,180,214,216,598,628,629,1058,1059,1637,2410,2903,2905')
```

En base a lo anterior se puede buscar un valor mínimo de score que no limite tanto el número de referencias por artículo.

**Comment by andres-linares** [comment]
Estadísticas:
- Existen 88233 referencias en simbad para los 7840 objetos NGC (sin repetirse).
- 28561 referencias no tienen score (%32.3)
- 59672 referencias tienen un score mayor o igual a 1 (%67.6)
- 53394 referencias tienen un score mayor o igual a 2 (%60.5)
- 48528 referencias tienen un score mayor o igual a 4 (%54.9)
- 45449 referencias tienen un score mayor o igual a 8 (%51.5)
- 43681 referencias tienen un score mayor o igual a 16 (%49.5)
- 40755 referencias tienen un score mayor o igual a 32 (%46.1)
- 27829 referencias tienen un score mayor o igual a 64 (%31.5)
- 10329 referencias tienen un score mayor o igual a 128 (%11.7)
- 6291 referencias tienen un score mayor o igual a 256 (%7.1)
- 3945 referencias tienen un score mayor o igual a 512 (%4.4)
- 2133 referencias tienen un score mayor o igual a 1024 (%2.4)
- 762 referencias tienen un score mayor o igual a 2048 (%0.8)
- 124 referencias tienen un score mayor o igual a 4096 (%0.0)

Sin embargo, aún falta explorar cuantas referencias tienen asociado un **Full paper** y cuantos son de **libre acceso**.
