### ISSUE TITLE
Reportar actividades

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#157]
Daniel y Wildimar,

Por favor generar un reporte de las actividades realizadas desde el primer corte. 

Incluir el tiempo de respuesta a las solicitudes realizadas por otros miembros de equipo por otros canales (Ej: Email, Github, Whatsapp, etc.). ¿Cuanto tiempo se están demonado en atender los requerimientos de sus compañeros?

Muchas gracias.
--Javier

**Comment by hamiltonsalazar** [comment]
No se presentan reportes, se cierran por tiempo
