### ISSUE TITLE
Implementar parafraseo

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#158]
Por favor implementar parafraseo de oraciones de acuerdo al siguiente código:

https://github.com/jmencisom/nb-opt/blob/master/08-parafraseo.ipynb

Gracias

**Comment by LinaMejia** [comment]
las palabras parafraseables son:
JJ: adjective or numeral, ordinal
JJR: adjective, comparative
JJS: adjective, superlative
NNS: noun, common, plural
RB: adverb
RBR: adverb, comparative
RBS: adverb, superlative
RP: particle
VB: verb, base form

![image](https://user-images.githubusercontent.com/33190990/41180405-cb135764-6b33-11e8-920c-116714d229a8.png)

la salida es un arreglo (paraphrasedText) con tantas posiciones como textos filtrados por la expresión regular hecha por Francisco.
La función a la que se envía el texto filtrado:
![image](https://user-images.githubusercontent.com/33190990/41180910-788faedc-6b35-11e8-855b-3ce5a15ecaee.png)
así llamo a la función:
![image](https://user-images.githubusercontent.com/33190990/41180959-a879891a-6b35-11e8-8080-c89d9810caf8.png)

**el  commit está en la rama text_extraction y el código sigue en el archivo .ipynb**

**Comment by jmencisom** [comment]
Muy bien Lina. Gracias por el aporte!
