### ISSUE TITLE
Compartir texto artículo

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#159]
Luis Carlos.

Por favor compartir el avance (Link?) del artículo.

Gracias.
--Javier

**Comment by luiscarlosmartg** [comment]
el articulo fue compartido por el correo

**Comment by hamiltonsalazar** [comment]
No se evidenció ningún reporte de ello en las debidas tareas, estas no se puede contar como labores cumplidas. El documento en Drive para ellos igualmente se encuentra vacío.
Le recuerdo @luiscarlosmartg que los miembros de equipo sólo pueden mover las tareas a hechas, más no cerrarlas, estas son labor de su respectivo líder de equipo @andres-linares  o @fraroca97 como administrador del GitHub.

**Comment by hamiltonsalazar** [comment]
Hasta no generarse un debido reporte la issue no puede contar como culminada con algún responsable, simplemente se cierra por ahora por tiempo con ningún responsable a su cargo.
