### ISSUE TITLE
Agregar opciones a comando

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#160]
$ python wikastro.py --version (Muestra la version del script 1.0)

$ python wikastro.py --help (Muestra las opciones diponibles)

http://www.diveintopython.net/scripts_and_streams/command_line_arguments.html

**Comment by andres-linares** [comment]
![imagen](https://user-images.githubusercontent.com/15129146/40337196-be511bd2-5d33-11e8-9841-244b095e7b08.png)
something like this?

**Comment by jmencisom** [comment]
Yes. Remember we should run the script by calling wikastro.py, which in
turn will call NGC.py (or other catalog scripts we will develop in future).

Thank you.
Javier
