### ISSUE TITLE
Mejorar el proceso de obtención del descubridor y la fecha de descubrimiento.

### ISSUE THREAD

**Issue by fraroca97** [jmencisom/wikastro#161]
En respuesta a las recomendaciones dadas por el ingeniero @jmencisom se crea la necesidad de mejorar la forma en que son obtenidos estos datos.

**Comment by LinaMejia** [comment]
Estoy trabajando ahora con un archivo de texto plano delimitado por "|".
![image](https://user-images.githubusercontent.com/33190990/40450150-61a9de8c-5ea0-11e8-841e-30b864c70dce.png)

separo la línea que necesito y luego hago split para llegar al descubridor y año. También queda el archivo guardado en la carpeta src y si no existe lo descargo, de lo contrario trabajo con el info.txt que haya en esta.
![image](https://user-images.githubusercontent.com/33190990/40450077-25d328f0-5ea0-11e8-997a-6224290f000a.png)
el resultado:
![image](https://user-images.githubusercontent.com/33190990/40450188-8426ba2a-5ea0-11e8-89c0-10a3b7ef17ba.png)

**Esto lo implementé en un archivo separado me faltaría implementarlo en el código del proyecto del curso**

**Comment by LinaMejia** [comment]
Código integrado.
![image](https://user-images.githubusercontent.com/33190990/40526291-28dc9a3e-5fab-11e8-9637-7c9105c83aff.png)
resultado.
![image](https://user-images.githubusercontent.com/33190990/40526318-5f75569e-5fab-11e8-8ed1-51346e0557d6.png)
-Elimino el uso de la librería xlrd por tanto queda removida del requirements.txt.

**Comment by andres-linares** [comment]
Acabo de ejecutar el script y no aparece información relacionada:
![imagen](https://user-images.githubusercontent.com/15129146/40632803-7a751616-62b0-11e8-8e2c-905b4d3fd517.png)

**Comment by LinaMejia** [comment]
eso es porque está ubicado en la carpeta src a la hora de ejecutar el wikastro.py y  la función busca el archivo así:  `.\src\info.txt` .

al ejecutar así python .\src\wikastro.py --ngc desde la carpeta wikastro no arroja ningún problema.

¿cambio la ubicación del archivo, que lo busque  en donde se esté ejecutando el programa?

**Comment by LinaMejia** [comment]
**así ya queda solucionado el problema:**
![image](https://user-images.githubusercontent.com/33190990/40693186-b31e9066-637b-11e8-8ed1-dff1149a119c.png)
