### ISSUE TITLE
Generar reporte con estadísticas del clasificador

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#162]
El reporte debe contener la **matriz de confusión** y un **reporte de clasificación** que contenga la precisión, el valor-F y la sensibilidad (en ingles: _precision_, _f1-score_ y _recall_)

**Comment by andres-linares** [comment]
La base de datos de entrenamiento (el archivo _training.csv_ en el repositorio) cuenta con **60 instancias**. Para obtener estadísticas con estas pocos datos, se hizo una división de datos de pruebas y datos de entrenamiento a razón de **1:4**.
Es decir, 15 frases fueron seleccionadas en el set de datos de prueba.

Las clases se distribuyeron equitativamente en los datos de prueba, sin embargo las frases pertenecientes a la clase fueron seleccionadas aleatoriamente.

Usando el clasificador **_Multinomial Naive Bayes_** se obtuvieron los siguientes resultados en la matriz de confusión y en el reporte de clasificación:
- Matriz de confusión: [(5, 0, 0), (1, 2, 2), (2, 0, 3)] con el orden _abstract_, _observation_ y _structure_. Por lo tanto se puede decir que de **5** frases que pertenecen al _abstract_ fueron reconocidas como tales; de **5** frases que pertenecen a _observation_ solo **2** fueron bien reconocidas; de **5** frases provenientes de la clase _structure_ solo **3** fueron bien reconocidas. Se puede observar un **sesgo** hacia la clase **_abstract_** y un bajo desempeño en la clase _**observation**_. Sin embargo la baja cantidad de datos puede ser el principal factor de estos resultados.
- Reporte de clasificación:
![imagen](https://user-images.githubusercontent.com/15129146/40693330-733e9846-637c-11e8-839b-78fdfd024676.png)

**Comment by jmencisom** [comment]
Muy bien @andres-linares. ¿Podríamos mejorar el clasificador con más datos de entrenamiento? @mejiajhonathan

**Comment by mejiajhonathan** [comment]
Si. En horas de la tarde, espero aumentar a por lo menos 30 datos por etiqueta  e ir aumentando...

**Comment by andres-linares** [comment]
Claro, con más datos el clasificador tendría un mejor rendimiento.
Nunca son demasiados datos para **_Machine Learning_**.

**Comment by mejiajhonathan** [comment]
Se hizo la actualización correspondiente a 50 datos por etiqueta. La información se encuentra en el siguiente enlace [Actualizacion datos clasificador](https://drive.google.com/file/d/1ukUcTYFHFjjsKilAPVdfmkLyCydT7WwJ/view?usp=sharing)

**Comment by andres-linares** [comment]
Con los nuevos datos, se obtiene las siguientes estadísticas:
![imagen](https://user-images.githubusercontent.com/15129146/40809061-d10093ee-64ee-11e8-8ee5-24ea3d0305ad.png)

Se sigue usando el mismo clasificador y una división de datos a razón de 1:4.

He leído algunos artículos y es común que antes de llevar el texto al clasificador o al predictor, se eliminen las _**Stop Words**_, en la literatura se habla de estas palabras como **ruido** y ahí la razón para eliminarlas.
