### ISSUE TITLE
Evaluar desempeño parafraseo

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#163]
El parafraseo se puede ver como un problema de clasificación donde la frase parafraseada se clasifica y la categoría resultante debe ser igual a la categoría de la oración original.

https://en.wikipedia.org/wiki/Paraphrasing_(computational_linguistics)#Evaluation

Por favor generar la matriz de confución para las oraciones parafraseadas. Las oraciones parafraseadas se obtienen después d aplicar la función de parafreseo al conjunto de datos de entrenamiento.

Muchas gracias.

@andres-linares por favor asignar a quien corresponda.

**Comment by hamiltonsalazar** [comment]
Se cierra por tiempo y dado que ya se envió el artículo.
