### ISSUE TITLE
Integrar ramificaciones del proyecto

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#164]
Por favor unificar todas las ramificaciones (branches) un la rama principal (master) antes de finalizar el proyecto.

Gracias.

**Comment by andres-linares** [comment]
¿Los _notebooks_ generados por **jupyter** los añado a la rama de master en algún nuevo directorio o que hago con ellos?

**Comment by andres-linares** [comment]
¿@georgebaron aún necesita las dos ramas?
