### ISSUE TITLE
Generar producción manual de articulo salida Wikipedia

### ISSUE THREAD

**Issue by mejiajhonathan** [jmencisom/wikastro#165]
Leer los pdfs, extraer oraciones que contienen el término "NGC...", asociar las oraciones para producir el texto para el articulo de Wikipedia y parafrasear las oraciones.

**Comment by mejiajhonathan** [comment]
Alguno del equipo de desarrollo @andres-linares, @fraroca97 o @LinaMejia podría colaborar diciéndome como extraer de los pdfs las oraciones que contienen la etiqueta "NGC" o que por favor me entregue las oraciones ya listas para analizar, actualmente llevo más de 2 horas extrayendo las oraciones de manera manual y solo llevo estas en la wiki: [Producción manual articulo Wikipedia](https://github.com/jmencisom/wikastro/wiki/Producci%C3%B3n-manual-articulo-Wikipedia) pero resultó ser muy tedioso, por lo que requiero de su ayuda para avanzar más rápidamente en el análisis de dichas frases para armar el articulo de salida y parafrasear este. 
*En ocasiones hay mas de 300 palabras NGC dentro de frases y hay mas de 200 PDFs a analizar.

**Comment by mejiajhonathan** [comment]
Después de un largo y tediosos análisis de los pdfs proporcionados, encontré 3 casos que pueden ser de bastante utilidad:

PRIMERO
Un pdf NGC_0104_048 aproximadamente 10 definiciones de diversos objetos NGC con su respectivo texto extraído y con imágenes que soportan su ubicación dentro del pdf (que servirá para reestructurar la forma en que se va a extraer las oraciones de estos mediante expresiones regulares).

SEGUNDO
De muchos de los PDFS analizados, solamente encontré 2 PDFS que hacen énfasis, cada uno, en un solo objeto NGC, pero eso no garantiza que la información nos vaya a servir.

TERCERO
Dado que en esos pdfs suelen hablarse de muchos objetos NGC, en unos de los casos, se pudo extraer información (diría yo) muy buena como que se pudo extraer informacion y caracteristicas de un solo OBJETO NGC.

Todos los resultados quedaron consignado en [Resultados Articulo Manual](https://github.com/jmencisom/wikastro/wiki/Resultados-Articulo-Manual), es IMPORTANTE SU REVISIÓN.

**NOTA:** El equipo de desarrollo considero debe reconsiderar la expresión regular en la que se debe extraer información asociada al término "NGC", ya que en muchos de los casos los artículos, éstos términos suelen estar en los subtitulos o pueden contener referencias de la forma (autor et al. año), por lo que puede que muchas veces las oraciones queden "cortadas

**Comment by mejiajhonathan** [comment]
Ingeniero @jmencisom quedo a la espera de que me confirme, según estos resultados, si sirve alguna de la información que quedó consignada en esa wiki sobre esos objetos para parafrasear, o que me diga cual de esos objetos considera usted tiene información "buena" (cual escogería?) para la captura de la salida que se anexará al articulo cientifico.

**Comment by mejiajhonathan** [comment]
Para parafrasear, casi no se encuentran los adjetivos a modificar, requeriría de la experta en parafraseo 
@LinaMejia  para verificar si esa salida es viable, ya que no se muy bien como implementarlo. De lo contrario @andres-linares utilice las frases que no están resaltadas en su totalidad para generar la salida con la clasificación de su algoritmo (quizás se puedan omitir cosas del texto, pero no cuento con otro criterio de ayuda para solucionar este problema).

*******TEXTOS********

**It is noted that NGC 4258 was observed with a F555W filter, while the other galaxies were observed with a F606W filter. In the case of NGC 300, we used a color interval of 0.15 mag because the CMD of this galaxy contains a much larger number of blue RGB stars.**

* NGC 4258 **has been** observed with a F555W filter, while the other galaxies were observed with a F606W filter.

**NGC 4258 is an important galaxy for calibration of both the color dependence and the zero-point, because it shows a broad range of RGB color and hosts a megamaser, which is useful for geometric distance estimation. NGC 4258 was observed with F555W and F814W filters.**

* NGC 4258 is an **essential** galaxy for calibration of both the color dependence and the zero-point, because it shows a broad range of RGB color and hosts a megamaser, which is useful for geometric distance estimation. NGC 4258 **has been** observed with F555W and F814W filters.

**In Paper III we presented F555W, F606W, and F814W band photometry of two Milky Way globular clusters, NGC 2419 and 47 Tuc. A large scatter of NGC 2419 stars at F606W F814W 0.5 - ~ mag is probably due to the RR Lyrae variables.**

* In **a** Paper III **they present** F555W, F606W, and F814W band photometry of two Milky Way globular clusters, NGC 2419 and 47 Tuc. A best scatter of NGC 2419 stars at F606W F814W 0.5 - ~ mag is probably due to the RR Lyrae variables.

**We shifted the TRGB magnitudes and corresponding fit results of each galaxy along the vertical direction, to be consistent with the result from NGC 4258, and plot them in Figure 5(a).**

* **They shift** the TRGB magnitudes and corresponding fit results of each galaxy along the upright direction, to be consistent with the result from NGC 4258, and plot them in Figure 5(a).

**The transformation was applied to seven galaxies that were observed with the F606W and F814W filters, excluding NGC 4258. NGC 4258 is known to be a useful distance anchor because it hosts a water megamaser, which can be used as a powerful and precise geometric distance indicator.**

* The transformation was applied to seven galaxies that were observed with the F606W and F814W filters, excluding NGC 4258. NGC 4258 is known to be a useful distance anchor because it hosts a water megamaser, which can be used as a powerful and precise geometric distance indicator.

**By monitoring observations of the nuclear water megamaser sources in NGC 4258, several geometric distance estimates were presented by Greenhill et al. (1995), Miyoshi et al. (1995), Herrnstein et al. (1999), Humphreys et al. (2005, 2008, 2013), Argon et al. (2007), and Riess et al. (2016). Humphreys et al. (2013) reported a distance value of d =  7.60 0.17 0.15 r s Mpc ((m M - = )0 29.404 0.049 0.043  r s), where errors with r and s represent random errors and systematic errors, respectively.**

* By monitoring observations of the nuclear water megamaser sources in NGC 4258, several geometric distance estimates were presented by Greenhill et al. (1995), Miyoshi et al. (1995), Herrnstein et al. (1999), Humphreys et al. (2005, 2008, 2013), Argon et al. (2007), and Riess et al. (2016). Humphreys et al. (2013) reported a distance value of d =  7.60 0.17 0.15 r s Mpc ((m M - = )0 29.404 0.049 0.043  r s), where errors with r and s represent **aleatory** errors and **standarized** errors, respectively.

**Mager et al. (2008) reported a TRGB distance to NGC 4258 based on photometry of the same HST images as used in this study. They showed that the T magnitude works well in the case of NGC 4258 (Mager et al. 2008; Madore et al. 2009). Figure 14 shows the propagation of the zero-point uncertainties in the previous calibration based on ω Centauri (circles, Bellazzini et al. 2001, 2004) and the revised QT calibrations based on NGC 4258 and the LMC in this study (triangles and squares).**

* Mager et al. (2008) reported a TRGB distance to NGC 4258 based on photometry of the same HST images as used in this study. They showed that the T magnitude works well in the case of NGC 4258 (Mager et al. 2008; Madore et al. 2009). Figure 14 shows the propagation of the zero-point uncertainties in the previous calibration based on ω Centauri (circles, Bellazzini et al. 2001, 2004) and the revised QT calibrations based on NGC 4258 and the LMC in this study (triangles and squares).

**On the other hand, the revised TRGB calibration in this study yields total systematic uncertainty of 0.073 mag from NGC 4258 and 0.096 mag from the LMC as described in Section 3.**

* On the other hand, the revised TRGB calibration in this study yields total efficient uncertainty of 0.073 mag from NGC 4258 and 0.096 mag from the LMC as described in Section 3.

**Comment by andres-linares** [comment]
- NGC 4258 has been observed with a F555W filter, while the other galaxies were observed with a F606W filter. **structure**
- NGC 4258 is an essential galaxy for calibration of both the color dependence and the zero-point, because it shows a broad range of RGB color and hosts a megamaser, which is useful for geometric distance estimation. **structure**
- NGC 4258 has been observed with F555W and F814W filters. **structure**
- In a Paper III they present F555W, F606W, and F814W band photometry of two Milky Way globular clusters, NGC 2419 and 47 Tuc. A best scatter of NGC 2419 stars at F606W F814W 0.5 - ~ mag is probably due to the RR Lyrae variables. **structure**
- They shift the TRGB magnitudes and corresponding fit results of each galaxy along the upright direction, to be consistent with the result from NGC 4258, and plot them in Figure 5(a). **structure**
- The transformation was applied to seven galaxies that were observed with the F606W and F814W filters, excluding NGC 4258. **observation**
- NGC 4258 is known to be a useful distance anchor because it hosts a water megamaser, which can be used as a powerful and precise geometric distance indicator. **structure**
- By monitoring observations of the nuclear water megamaser sources in NGC 4258, several geometric distance estimates were presented by Greenhill et al. (1995), Miyoshi et al. (1995), Herrnstein et al. (1999), Humphreys et al. (2005, 2008, 2013), Argon et al. (2007), and Riess et al. (2016). Humphreys et al. (2013) reported a distance value of d = 7.60 0.17 0.15 r s Mpc ((m M - = )0 29.404 0.049 0.043 r s), where errors with r and s represent aleatory errors and standarized errors, respectively. **observation**
- Mager et al. (2008) reported a TRGB distance to NGC 4258 based on photometry of the same HST images as used in this study. **observation**
- They showed that the T magnitude works well in the case of NGC 4258 (Mager et al. 2008; Madore et al. 2009). **abstract**
- Figure 14 shows the propagation of the zero-point uncertainties in the previous calibration based on ω Centauri (circles, Bellazzini et al. 2001, 2004) and the revised QT calibrations based on NGC 4258 and the LMC in this study (triangles and squares). **abstract**
- On the other hand, the revised TRGB calibration in this study yields total efficient uncertainty of 0.073 mag from NGC 4258 and 0.096 mag from the LMC as described in Section 3. **observation**

**Comment by jmencisom** [comment]
@mejiajhonathan @andres-linares cómo va la generación de la salida? Alguna hora estimada para entregar los pantallazos?

**Comment by mejiajhonathan** [comment]
@andres-linares  por favor generar la salida junto con la tabla de descripción evitando las frases que hacen referencia a figuras y tomar pantallazo en Wikipedia sobre como quedairs junto con él código que genera

**Comment by mejiajhonathan** [comment]
@andres-linares

**Comment by andres-linares** [comment]
![imagen](https://user-images.githubusercontent.com/15129146/40869085-a10aeb48-65da-11e8-8fd0-addd9b30bb58.png)
![imagen](https://user-images.githubusercontent.com/15129146/40869090-a82722f2-65da-11e8-9679-9b893b29e25c.png)

**Texto:**
```
{{Sky|12|18|57.620||+47|18|13.39|999}}

{{Infobox galaxy
| name = [[New General Catalogue|NGC]] 4258
| image = M106 (28308513951).jpg
| caption = NGC 4258 taken by [[]].<ref>{{cite web|title=123abc|url=abc123|website=a1b2c3|accessdate=1a2b3c}}</ref>
| epoch = [[J2000]]<ref name="simbad">{{cite web
  |title=SIMBAD Astronomical Database - CDS (Strasbourg)
  |work=Results for NGC 4258
  |url=http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=NGC+4258&submit=SIMBAD+search
  |accessdate=2018-06-01}}</ref>
| ra = {{RA|12|18|57.620}}<ref name="simbad" />
| dec = {{DEC|+47|18|13.39}}<ref name="simbad" />
| constellation name = Canes Venatici
| z = 0.001541<ref name="simbad" />
| h_radial_v = {{nowrap|462[[Metre per second|km/s]]}}<ref name="simbad" />
| type = SAB(s)bc <ref name="simbad" />
| appmag_b = 9.14<ref name="simbad" />
| dist_ly = 21.73 M[light-year|ly]
| discoverer = Pierre Mechain
| year of discovery = 1781
| names =  B3 1216+475, 7C 121635.39+473404.00, 7C 121626.19+473526.00, 7C 121620.39+473545.00, GB1 1216+476, GB6 B1216+4735, 87GB 121625.0+473537, LEDA 39600, [[2MASX]] J12185761+4718133, [[Morphological Catalogue of Galaxies|MCG]]+08-22-104, MY 121625.0+471813.7, [[New General Catalogue|NGC]] 4258, OHIO N 427, PBC J1218.9+4718, 1RXP J121856.4+471755, RX J1219.0+4717, RX J1218.9+4718, [[1RXS]] J121900.4+471747, SAX J1219.7+4721, SDSS J121857.50+471814.3, SWIFT J1218.9+4717, SWIFT J1219.4+4720, SWIFT J1219.0+4715, [[Uppsala General Catalogue|UGC]] 7353, UZC J121857.7+471820, VLSS J1218.9+4718, VV 448, WB 1216+4735, 2XMM J121857.5+471814, XSS J12190+4715, Z 243-67, Z 244-3, Z 1216.5+4735, [BAG2012] 184.7378+47.2874, [CHM2007] HDC 706 J121857.61+4718133, [CHM2007] LDC 867 J121857.61+4718133, [CPF88] 121629.0+473500.0, [KRL2007b] 111, [M98c] 121629.7+473455, [NKB95] N4258, [VDD93] 154, [VV2000c] J121857.5+471814, [VV2003c] J121857.5+471814, [VV2006c] J121857.5+471814, [VV2010c] J121857.5+471814, [VV98c] J121857.5+471814, [ZEH2003] RX J1219.0+4717 1<ref name="simbad" />}}
'''NGC 4258''', also occasionally referred to as '''[[Uppsala General Catalogue|UGC]] 7353''' and '''[[Morphological Catalogue of Galaxies|MGC]] +08-22-104''' is  a spiral galaxy located in the constellation of [[Canes Venatici]] at an aproximate distance of 27.73 M[[light-year|ly]]. NGC 4258 was discovered in 1781 by Pierre Mechain.

==Observation==
By monitoring observations of the nuclear water megamaser sources in NGC 4258, several geometric distance estimates were presented by Greenhill et al. (1995), Miyoshi et al. (1995), Herrnstein et al. (1999), Humphreys et al. (2005, 2008, 2013), Argon et al. (2007), and Riess et al. (2016). Humphreys et al. (2013) reported a distance value of d = 7.60 0.17 0.15 r s Mpc ((m M - = )0 29.404 0.049 0.043 r s), where errors with r and s represent aleatory errors and standarized errors, respectively. Mager et al. (2008) reported a TRGB distance to NGC 4258 based on photometry of the same HST images as used in this study. On the other hand, the revised TRGB calibration in this study yields total efficient uncertainty of 0.073 mag from NGC 4258 and 0.096 mag from the LMC as described in Section 3.

==Structure==
NGC 4258 is an essential galaxy for calibration of both the color dependence and the zero-point, because it shows a broad range of RGB color and hosts a megamaser, which is useful for geometric distance estimation. NGC 4258 has been observed with F555W and F814W filters. NGC 4258 is known to be a useful distance anchor because it hosts a water megamaser, which can be used as a powerful and precise geometric distance indicator.

==See also==
*[[Galaxy]]

==External links==
*[http://simbad.u-strasbg.fr/simbad/sim-basic?Ident=NGC+4258&submit=SIMBAD+search NGC 4258 on SIMBAD]

==References==
{{reflist}}
[[Category:NGC objects|4258]]

{{commonscat}}
{{Galaxy}}
{{Ngc45}}
```

**Comment by andres-linares** [comment]
![imagen](https://user-images.githubusercontent.com/15129146/40869173-bfd7dc60-65db-11e8-9577-7ae7111dd4a0.png)
Imagen de como se ve (no tengo cuenta así que no puedo cambiar el título al editar)

**Comment by mejiajhonathan** [comment]
@jmencisom

**Comment by jmencisom** [comment]
Cometi un error. El objeto NGC 4258 ya existe en Wikipedia https://en.wikipedia.org/wiki/Messier_106. Podemos usar otro que no exista?

**Comment by jmencisom** [comment]
Que tal https://en.wikipedia.org/wiki/NGC_425? Aunque la pagina NGC 425 ya existe, la versión generada automaticamente tiene mas texto

**Comment by mejiajhonathan** [comment]
El objeto NGC del que se tiene información es NGC 4258. Del NGC 425 no se tiene información.

**Comment by jmencisom** [comment]
Tiene razon... vuelvo a cometer el error. Lo que pasa es que en la wiki aparece 425 en el titulo https://github.com/jmencisom/wikastro/wiki/Resultados-Articulo-Manual#ngc-425, pero se refiere a 4258.

Que otro NGC podemos usar que no tenga una pagina tan extensa? https://en.wikipedia.org/wiki/NGC_1856

**Comment by mejiajhonathan** [comment]
Si, esa es viable debido al alto contenido de información.
**TEXTO SIN PARAFRASEAR OBJETO NGC 1856**

The recent discovery of double main sequences in the young, massive star cluster NGC 1856 has caught significant attention.

We analyzed the number ratios of stars belonging to both main-sequence components in NGC 1856 as a function of radius Through a comparison of the loci of the best-fitting isochrones with the ridge lines of both stellar components, we found that both multiple stellar populations and rapid stellar rotation can potentially explain the observed main-sequence bifurcation in NGC 1856.

However, if NGC 1856 were a young representative of the old globular clusters, then the multiple stellar populations model would not be able to explain the observed homogeneity in the spatial distributions of these two components, since all relevant scenarios would predict that the second stellar generation should be formed in a more compact configuration than that of the first stellar generation, while NGC 1856 is too young for both stellar generations to have been fully mixed dynamically.

We speculate that the rapid stellar rotation scenario would be the favored explanation of the observed multiple stellar sequences in NGC 1856.

The first evidence of possible multiple stellar populations in young clusters was discovered in the Large Magellanic Cloud cluster NGC 1856 (Correnti et al. 2015; Milone et al. 2015a).

Similar to NGC 1856, it was found that the YMC NGC 1755 also exhibits an apparent bifurcation in its MS (Milone et al. 2016).

Although there is growing evidence of the reality of multiple stellar populations in YMCs, the dynamics of these different stellar populations are still poorly understood. In this paper, we analyze the radial profile of the number ratio of the two MS components in NGC 1856.

Two equally likely scenarios could potentially explain the observed multiple MS components in NGC 1856: the observed multiple sequences can be explained by either invoking multiple stellar populations of different ages and metallicities, or a coeval stellar population characterized by member stars that exhibit two different rotation rates (D’Antona et al. 2015).

However, if the former explanation were correct, and if NGC 1856 is indeed the infant stage of an old GC, the second-generation stars should be initially more centrally concentrated than their first-generation counterparts (Renzini 2008; Vesperini et al. 2013; Hénault-Brunet et al. 2015; Khalaj & Baumgardt 2015).
 
Since NGC 1856 is very young (∼300 Myr; Milone et al. 2015a), this difference in their radial distributions should be still apparent, but this prediction is in conflict with our observations.

Our result may indicate that the observed multiple stellar sequences in NGC 1856 have actually been produced by a coeval stellar population composed of two components of stars with different rotation rates.

The method we used to determine the stellar number-density center in NGC 1856 is identical to that of Li et al. (2016): we first divided all stars into 20 bins along both the right ascension (aJ2000) and declination (dJ2000) axes.

This procedure provided us with a monotonically decreasing number-density profile of the stars in NGC 1856.

The color separation between both MS components in NGC 1856 reaches 0.1 mag or more.
However, because the red-component stars dominate the stellar numbers at a given magnitude, this means most binaries in NGC 1856 must be high mass-ratio binary systems.

If the observed double sequences in NGC 1856ʼs CMD can be explained by single stars (blue sequence) and binaries (red sequence), stars that belong to the red MS component should be more segregated than the bluepopulation stars. This is in contrast to our results.

Two scenarios could potentially explain the MS split in the CMD of NGC 1856: (1) multiple stellar populations of different ages and metallicities or (2) a coeval stellar population composed of two stellar components that are distinctly different in terms of their rotation properties.

For young stellar clusters like NGC 1856, the MS regime studied in this paper is populated by very hot stars. This figure clearly shows that helium differences cannot reproduce the large MS color split observed in NGC 1755, NGC 1856, and other young clusters in the Magellanic Clouds.

This may further indicate that NGC 1856 could have retained the initial runaway gas from supernova explosions, since the two observed stellar populations are different in their [Fe/H] abundances.

Finally, we conclude that NGC 1856ʼs initial mass should be at least M M cl ~ ´ 7.76 10  6 to retain the runaway gas driven by SNe II.

The current mass of NGC 1856 is of order 10 M 5 (McLaughlin & van der Marel 2005), while the enhanced metallicity of the second stellar generation in NGC 1856 would indicate that it has lost more than 99% of its initial mass during the last 340 Myr.

However, the half-mass relaxation timescale for stars in NGC 1856 is thm = 2.2 Gyr (McLaughlin & van der Marel 2005), which is roughly seven times longer than the isochronal age of the cluster.

However, all these speculations are based on the assumption that NGC 1856 is actually a young counterpart of the old GCs. It is also possible that the results from NGC 1856 cannot provide any constraints to the scenarios for multiple stellar populations in old GCs, given that all scenarios we have discussed deal with old GCs (Renzini 2008; Vesperini et al. 2013; Hénault-Brunet et al. 2015; Khalaj & Baumgardt 2015).

Based on all the considerations, we conclude that the MS bifurcation in NGC 1856 is most likely not caused by multiple stellar populations of different ages and metallicities.

D’Antona et al. (2015) explored the impact of rapid stellar rotation to explain the observed split in the MS of NGC 1856. They found that the observed CMD of NGC 1856 can be interpreted as a coeval stellar population composed of one-third of slowly/nonrotating stars and two-thirds of very rapidly rotating stars.

If rotational mixing also plays a significant role in rapidly rotating stars in NGC 1856, then a less massive rapidly rotating star would have the same luminosity as a more massive nonrotating star, because the former has the same core size as the latter. In this paper, we have constrained our study of the two stellar components to the same magnitude range, which means that if rotational mixing is important for the red-component stars, their average mass should be smaller than that of the blue-component stars. In turn, this would lead to the former becoming less segregated than the blue stellar population.

In this paper, we have studied the number ratio of stars belonging to two distinct components of NGC 1856ʼs MS.

We found a reliable number ratio of the blue and red MS component stars in NGC 1856 of 34%/66%.

We emphasize that this conclusion is based on the assumption that NGC 1856 is representative of a young counterpart to the old GCs.

**Comment by mejiajhonathan** [comment]
Se reemplazaron las palabras **We** por **they** y se hicieron algunas modificaciones de tiempos verbales. @andres-linares nuevamente es necesaria su ayuda para la clasificación del texto y la generación del script para volver a tomar el pantallazo al objeto **NGC 1856**

**Comment by jmencisom** [comment]
Tiempo estimado @andres-linares ?

**Comment by jmencisom** [comment]
Artículo enviado

**Comment by andreveca** [comment]
Se da por culminada la tarea.
