### ISSUE TITLE
Reparar archivo test.py

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#166]
![fireshot capture 013 - jmencisom_wikastro - travis ci - https___travis-ci org_jmencisom_wikastro](https://user-images.githubusercontent.com/1332546/40978307-f017d852-6898-11e8-80fa-68f56f76a035.png)

**Comment by jmencisom** [comment]
https://travis-ci.org/jmencisom/wikastro

**Comment by georgebaron** [comment]
@andres-linares  ya soluciono el problema con el travis
