### ISSUE TITLE
Realizar entrega final

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#170]
Teniendo en cuenta que la fecha de entrega final se ha aplazado dos veces (1ra: 5 Junio; 2da: 12 Junio), se establece el jueves 14 de Junio, 12 m como último plazo.

Muchas gracias por su colaboración.

@danielmrno @wildimarnieto @andres-linares @LinaMejia @luiscarlosmartg @andreveca @georgebaron @fraroca97 @mejiajhonathan

**Comment by hamiltonsalazar** [comment]
La entrega se realizará el día de mañana 15 de junio a las 5:30 PM, ya que el día de hoy no se pudo realizar por tiempos.
