### ISSUE TITLE
Realizar revisión de requerimientos

### ISSUE THREAD

**Issue by fraroca97** [jmencisom/wikastro#18]
Se hace necesario la actualización de los requerimientos actuales. Siendo más específicos en algunos de los existentes y agregando algunos que no fueron tomados en cuenta aún (como la documentación y la calidad)

**Comment by andres-linares** [comment]
Y agregar lo del STUB

**Comment by hamiltonsalazar** [comment]
@fraroca97 por favor verificar los requerimientos que usted consideró repetidos y dejar lo que plasmó en el tablero de clase el día 28-02-2018, agregando el requerimiento al que se refiere @andres-linares : "Asegurar que la salida no es un STUB" #4

**Comment by hamiltonsalazar** [comment]
Muchas gracias @fraroca97, se cumple con lo solicitado.
