### ISSUE TITLE
Agregar foto al perfil 

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#2]
Por favor agregar la foto al perfil en Github. Gracias

**Comment by hamiltonsalazar** [comment]
Muchachos fecha limite para actualización de foto de perfil el día de hoy.

**Comment by jmencisom** [comment]
@wildimarnieto y @luiscarlosmartg foto?

**Comment by jmencisom** [comment]
¿@wildimarnieto ha tenido dificultades para cambiar la foto? ¿En qué podrian ayudarle sus compañeros @hamiltonsalazar?

**Comment by hamiltonsalazar** [comment]
El compañero @wildimarnieto  no ha reportado actividad alguna en el Git, ni en el grupo donde se les da la información. Ya se le ha hecho la solicitud más de una vez, pero no ha contestado y desconozco (debido a su no reporte de actividad) si ya inició alguna de las tareas asignadas.

**Comment by fraroca97** [comment]
En vista de que el único integrante del equipo que faltaba ya tiene foto, la incidencia se ha movido a "Done" para un chequeo final y posterior cierre.

**Comment by hamiltonsalazar** [comment]
Perfecto. Todas ya cuentan con la foto.
