### ISSUE TITLE
Compartir URL hoja de cálculo

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#20]
Por favor compartir URL de la hoja de cálculo donde se registra diariamente el avance del grupo.

j4r.e4o@gmail.com

Gracias.

**Comment by jmencisom** [comment]
Tiene dificultades con la conexión?

**Comment by mejiajhonathan** [comment]
Donde nos conectamos? Como es lo de la clase virtual?

**Comment by jmencisom** [comment]
Gracias Jhonathan por el interés. Estoy esperando me compartan la hoja de cálculo donde está el resumen del trabajo del grupo. Sabe usted sobre ese documento?

**Comment by mejiajhonathan** [comment]
El gerente del proyecto es el que tiene el link de conexión del documento. No se en que URL se encuentra

**Comment by jmencisom** [comment]
OK, gracias Jhonathan. Por favor refinar la definició de la tarea https://github.com/jmencisom/wikastro/issues/8, Ej: Descomponer en subtareas realizables con tiempos cortos

**Comment by hamiltonsalazar** [comment]
Que pena la hora de reportarme, no tenía acceso a internet. @mejiajhonathan se encontraba compartida a los correos de todos nosotros desde el día que se creo 21 de febrero, sólo hacía falta el ingeniero y lo acabo de hacer.

**Comment by jmencisom** [comment]
Perfecto Hamilton. Muchas gracias por el compromiso!
