### ISSUE TITLE
Número de tareas "in progress"

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#21]
Buenas tardes.

El número de tareas "in progress" debe ser mayor o igual la número de integrantes del equipo.

Actualmente solo aparecen 5 tareas  "in progress" https://github.com/jmencisom/wikastro/projects/1, ¿qué sucede con las tareas de los demás (5) miembros del equipo?

Gracias.
--Javier

**Comment by hamiltonsalazar** [comment]
Actualmente se encuentra en la cantidad correcta, se estará realizando una revisión constante para cumplir con ello durante todo el desarrollo del proyecto.
