### ISSUE TITLE
Aprender a manejar la herramienta Sphinx-PARTE 1.

### ISSUE THREAD

**Issue by fraroca97** [jmencisom/wikastro#25]
En orden del cumplimiento del requerimiento RN11, se hace necesaria la apropiación de esta herramienta. Aprender acerca del uso de Sphinx para la documentación de métodos y clases y compartir dicho conocimiento con el resto del equipo lo más pronto posible.

**Comment by andres-linares** [comment]
Creo que podemos partir este Issue en dos: Una primera parte que se refiera al uso de Sphinx exclusivamente para la documentación de métodos y clases (que es algo necesario justo ahora) y otra parte que es para la documentación del proyecto en general.
Una vez que se cumpla la primera parte, se podrá asignar a una persona del equipo de pruebas para que trabaje sobre la documentación del código y convierta (transcriba, modifique) la forma como se comenta actualmente a la forma como se debe comentar con Sphinx

**Comment by hamiltonsalazar** [comment]
@georgebaron debido a las circunstancias y que se requiere de manera urgente, idear la forma de instruirnos en el manejo de ésta a través de medios digitales como una presentación, tutorial o videoconferencia, según lo crea más conveniente para no esperar hasta un próximo encuentro.

**Comment by andres-linares** [comment]
Para poder avanzar un poco en la documentación de los métodos y clases...
¿Qué estilo de documentación usa **Sphinx**?

En el ejemplo que subió el profesor, se observa que siguen el estilo de numpy. En caso de ser así, ¿podemos comenzar a cambiar la forma de documentar por la del estilo numpy?

**Comment by hamiltonsalazar** [comment]
@andres-linares mañana se realizará la socialización, allí puede realizar las respectivas sugerencias y aportes que tenga, para dar paso a la segunda etapa de esta.
