### ISSUE TITLE
Establecer las consecuencias ocasionadas por múltiples consultas. 

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#29]
Consultar cuales son las consecuencias y si hay problemáticas o limitantes para el desarrollo del proyecto, la realización de múltiples consultas desde una misma dirección y las posibles soluciones a éste.

**Comment by fraroca97** [comment]
Título ajustado.

**Comment by hamiltonsalazar** [comment]
¿algún avance? @wildimarnieto

**Comment by hamiltonsalazar** [comment]
@wildimarnieto después de un mes, ¿reporte alguno?

**Comment by hamiltonsalazar** [comment]
@wildimarnieto necesitamos reporte alguno en ésta Issue, acá en algún comentario además del ya asignado en la Issue #107 para así dar culminada y cerrada esta y la del reporte también.

**Comment by hamiltonsalazar** [comment]
No se presenta reporte.
