### ISSUE TITLE
Atrapar excepción cuando no hay conexión a internet

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#3]
Actualmente, en caso de no haber internet, el programa mostrará una excepción: **atraparla**

**Comment by jmencisom** [comment]
de igual forma se debe lanzar una excepción cuando el objeto astronómico no exista. Gracias

**Comment by andres-linares** [comment]
@jmencisom El script actual informa cuando el objeto no se encuentra en la base de datos de _simbad_
Sin embargo, en tiempo futuro, este caso deberá lanzar una excepción que deba ser atrapada en el código principal.
