### ISSUE TITLE
Definir presupuesto

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#30]
Definir el presupuesto del proyecto.

**Comment by fraroca97** [comment]
Título ajustado.

**Comment by hamiltonsalazar** [comment]
Se encuentra en espera, mientras se obtiene el valor de las consultas con el experto.

**Comment by hamiltonsalazar** [comment]
El presupuesto me hes entregado el día de ayer por la encargada de éste @andreveca que junto con mi apoyo y el aval del profesor lo damos por terminado, próximamente se hará público.

**Comment by hamiltonsalazar** [comment]
Por las dificultades de bisualización de éste mediante una Wiki, se comparte acá el link donde se puede observar en detalle el presupuesto. 
[https://docs.google.com/spreadsheets/d/1_wEAmrw4fQMsXJd1mbP2UUTmVXbFTMxZIoC11ri53UM/edit?usp=sharing](url)
