### ISSUE TITLE
Relacionar los tipos de objetos astronómicos que se encuentran en Wikipedia con los tipos de objetos NGC de Simbad y dejarlo en la Wiki.

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#33]

**Comment by mejiajhonathan** [comment]
Ya hice la relación de los tipos de objetos de SIMBAD con las categorías de WIKIPEDIA. Los resultados no son muy concluyentes, encontré tres tipos de relaciones: uno a uno, uno a muchos, y uno a ninguno. Los resultados los dejé en la Wiki en la pestaña relación tipos de objetos SIMBAD, plantillas de Wikipedia.

**Comment by mejiajhonathan** [comment]
Puedo hacer lo de las plantillas de las categorías que tienen relación uno a uno, pero no se que hacer con las relaciones uno a ninguno o uno a muchos. Qué me recomiendan? que hago?

**Comment by andres-linares** [comment]
El equipo de **análisis de datos** es el encargado de dar una solución.

Con el equipo de desarrollo ya estamos llegando al punto donde la solución a este issue será un paso necesario para poder avanzar....

**Comment by mejiajhonathan** [comment]
El equipo de análisis de datos no ha dado solución o aprobación a las plantillas que ya fueron subidas. @danielmrno

**Comment by hamiltonsalazar** [comment]
¿Algún avance @danielmrno ?

**Comment by hamiltonsalazar** [comment]
@danielmrno tenemos algún reporte, hace 27 días fue asignada la labor, requiere algo adicional o que obstrucción ha tenido hasta el momento que le impida el desarrollo de ésta.

**Comment by mejiajhonathan** [comment]
El ingeniero @jmencisom propuso manejar las plantillas que se relacionan a continuación:
[Template Galaxy](https://en.wikipedia.org/wiki/Template:Infobox_galaxy)
[Template Galaxy Cluster](https://en.wikipedia.org/wiki/Template:Infobox_galaxy_cluster)
[Template Open Cluster](https://en.wikipedia.org/wiki/Template:Infobox_open_cluster)
[Template Star](https://en.wikipedia.org/wiki/Template:Infobox_star)
[Template Globular Cluster](https://en.wikipedia.org/wiki/Template:Infobox_globular_cluster)

@andres-linares.

**Comment by mejiajhonathan** [comment]
@hamiltonsalazar considero que ya puede ser cerrado este issue.

**Comment by hamiltonsalazar** [comment]
@mejiajhonathan muchas gracias.
