### ISSUE TITLE
Corregir salida de las otras designaciones de un objeto NGC

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#36]
En las otras designaciones, el nombre **NGC** no debería aparecer Esto puede ser corregido desde el script en simbad (no estoy seguro, pero puede ser) o desde el código.
Por concordancia deberíamos tratar de llevar el mismo estilo que los primeros objetos de NGC:
![image](https://user-images.githubusercontent.com/15129146/37012900-f702788c-20c4-11e8-9503-d9f52c0eb568.png)
Separación por comas y, además, puede notarse que el primer nombre de una designación tiene como un hipervinculo. _(No estoy seguro si eso se hace añadiendo un **[[nombre]]** en lo que quiere que se haga un hipervinculo, como en **[[J2000]]** epoch)_

**Comment by fraroca97** [comment]
La funcionalidad de agregar las referencias conocidas para las otras designaciones fue añadida.

La incidencia fue movida a "Done" para una revisión por parte de @andres-linares y el posterior cierre o rechazo de la misma.

**Comment by andres-linares** [comment]
La solución es acorde al issue.
## Muestra:
![image](https://user-images.githubusercontent.com/15129146/37070082-f300d9ee-2183-11e8-8463-90f476a5f9ea.png)
