### ISSUE TITLE
Calcular estadísticas artículos

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#39]
Seleccionar aleatoriamente 20 artículos aprobados en la conferencia https://aclanthology.coli.uni-saarland.de/events/emnlp-2017 y calcular: 

1. promedio de autores por artículo.
1. promedio de referencias por artículo.
1. promedio de palabras por artículo

En general, ¿cuáles son las secciones que componen los artículos?

¿Estamos mas cerca de este tipo de artículos (Demostraciones de sistemas) https://aclanthology.coli.uni-saarland.de/events/emnlp-2017#D17-2 ?

Muchas gracias.

**Comment by danielmrno** [comment]
Anthology | Title | Autors | References
-- | -- | -- | --
D17-2001 | The NLTK   FrameNet API: Designing for Discoverability with a Rich Linguistic Resource | 2 | 13
D17-2002 | Argotario:   Computational Argumentation Meets Serious Games | 6 | 34
D17-2003 | An Analysis and   Visualization Tool for Case Study Learning of Linguistic Concepts | 3 | 9
D17-2004 | GraphDocExplore:   A Framework for the Experimental Comparison of Graph-based Document   Exploration Techniques | 2 | 19
D17-2005 | SGNMT – A   Flexible NMT Decoding Platform for Quick Prototyping of New Models and Search   Strategies | 4 | 23
D17-2006 | StruAP: A Tool   for Bundling Linguistic Trees through Structure-based Abstract Pattern | 6 | 13
D17-2007 | KnowYourNyms?   A Game of Semantic Relationships | 9 | 14
D17-2008 | The Projector:   An Interactive Annotation Projection Visualization Tool | 2 | 28
D17-2009 | Interactive   Visualization for Linguistic Structure | 6 | 10
D17-2010 | DLATK:   Differential Language Analysis ToolKit | 6 | 35
D17-2011 | QUINT:   Interpretable Question Answering over Knowledge Bases | 4 | 19
D17-2012 | Function   Assistant: A Tool for NL Querying of APIs | 2 | 8
D17-2013 | MoodSwipe: A   Soft Keyboard that Suggests MessageBased on User-Specified Emotions | 7 | 25
D17-2014 | ParlAI: A   Dialog Research Software Platform | 8 | 17
D17-2015 | HeidelPlace: An   Extensible Framework for Geoparsing | 4 | 12
D17-2016 | Unsupervised,   Knowledge-Free, and Interpretable Word Sense Disambiguation | 8 | 18
D17-2017 | NeuroNER: an   easy-to-use program for named-entity recognition based on neural networks | 3 | 36
D17-2018 | SupWSD: A   Flexible Toolkit for Supervised Word Sense Disambiguation | 3 | 22
D17-2019 | Interactive   Abstractive Summarization for Event News Tweets | 6 | 10
D17-2021 | Interactive   Visualization and Manipulation of Attention-based Neural Machine Translation | 3 | 16
  | Average | 4,7 | 19,05

**Comment by danielmrno** [comment]
- El promedio de palabras es un valor cercano a las 3000 palabras 

- Este tipo de artículos son los mas cercanos al tipo de proyecto que manejamos ya que en estos se agrega código, Screenshots del funcionamiento en aplicaciones y links a repositorios donde se trabaja

**Comment by jmencisom** [comment]
Muy bien. Entonces nos vamos un artículo de unas 3000 palabras con 15 referencias.

Pendiente: discusión sobre aporte de los autores del artículo científico.
Pendiente: publicar una artículo de caracter informativo con los demás estudiantes.

**Comment by jmencisom** [comment]
El artículo de caracter informativo lo podemos enviar a https://www.capjournal.org/submission.php

Los autores del artículo científico son:
Andrés Linares, Hamilton Salazar, Daniel Moreno, Javier Enciso

Los autores del artículo informativo son:
El resto del equipo, Javier Enciso
