### ISSUE TITLE
Asegurar que la salida NO es un STUB

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#4]
Asegurar que el artículo producido supera los requisitos para NO ser considerado como un STUB

https://en.wikipedia.org/wiki/Wikipedia:Stub

Muchas gracias.

**Comment by andres-linares** [comment]
En base al contenido en Wikipedia sobre **STUB** se puede decir, de manera general, que algunas métricas que han de cumplirse para que el artículo no sea considerado como **STUB** son:

1.  El artículo contendrá más de 10 oraciones.
2.  El artículo contendrá más de 250 palabras.
3.  El artículo contendrá más de 1500 caracteres.
4.  El artículo contendrá más de 500 palabras (_explicado a continuación_).

Si bien el punto número 4 parece estar en conflicto con el 2, lo que sucede es que los tres primeros puntos son "reglas" en las que se suelen basar los editores al considerar un artículo como **STUB** y el 4to punto es un proceso automático que hace la Wikipedia con sus artículos.
**_Es necesario aclarar que si bien la cantidad de texto es un factor a considerar,  dependiendo de la materia, el texto necesario puede ser menor._** 



> 'lists, templates, images, and other such peripheral parts of an article are usually not considered when judging whether an article is a stub.' [https://en.wikipedia.org/wiki/Wikipedia:Stub#How_big_is_too_big?](url)

Por tanto, las métricas se calcularán al momento de extraer el contenido de la base de datos y no cuando se obtenga el texto a pegar en la Wikipedia.

## Para el equipo de trabajo
### Equipo de Requerimientos
Deberá ser añadido en el documento de requerimientos el título de este Issue.
### Equipo de Desarrollo. División obtención de datos
Será completamente necesario extraer información de las referencias bibliográficas asociadas a los objetos NGC y calcular las métricas para asegurar que la información sea suficiente como para reducir al mínimo la probabilidad de que el artículo sea considerado como **STUB**.
### Equipo de Desarrollo. División generación de WikiTexto.
El texto generado deberá tener referencias puesto que los editores suelen tomar un artículo con pocas o nulas referencias como **STUB** e incluso puede ser directamente **ELIMINADO**.
