### ISSUE TITLE
Atrapar excepción al buscar NGC 1

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#41]
Al buscar el objeto NGC 1 aparece un **unicodeEncodeError**. Encontrar una solución

**Comment by hamiltonsalazar** [comment]
@fraroca97  manifiesta que se dedicará a la tarea este fin de semana.

**Comment by andres-linares** [comment]
Me estaba molestando un poco el bug así que decidí buscar una solución (Y)

**Comment by andres-linares** [comment]
Al parecer corrige el error pero elimina muchos caracteres de utf-8 como las tildes y otras cosas 😅
