### ISSUE TITLE
Buscar una base de datos que permita obtener la constelación del objeto NGC

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#42]
Complementar y hacer revisión respecto a lo actual.

**Comment by jmencisom** [comment]
http://docs.astropy.org/en/stable/api/astropy.coordinates.get_constellation.html

**Comment by andreveca** [comment]
``` python
from astropy.coordinates import SkyCoord, get_constellation
ra='11h55m45s'
dec='+55d19m14s'
c = SkyCoord(ra, dec, frame='icrs')
get_constellation(c)
```

**Comment by fraroca97** [comment]
Como **nota especial**, ahora se añadirá a los requisitos (requirements.txt) la librería astropy. Para evitar problemas durante la instalación de la librería (pip install astropy), en windows es necesario tener instalado "Microsoft Visual C++ Compiler for Python 2.7" que puede ser descargado desde el siguiente enlace:

(aka.ms/vcpython27)
