### ISSUE TITLE
Buscar una base de datos que permita obtener la distancia en años luz.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#43]

**Comment by andres-linares** [comment]
También puede estar en Megaparsec (mpc) y posteriormente hacer una conversión a años luz.

**Comment by andres-linares** [comment]
Encontrar formula para llevar de Redshift (dato que se encuentra en simbad) a años luz

**Comment by mejiajhonathan** [comment]
Observando en la sección “Collections of Measurements”, se encuentra un checkbox con dos opciones a seleccionar: “distance” o “velocities”. Al seleccionar alguna y posteriormente seleccionar uno de los botones que aparecen a continuación: “display selected measurements” o “display all measurementes”, según la búsqueda, lista todos los posibles valores de la magnitud física seleccionada. Tal como se muestra en la imagen:
![image](https://user-images.githubusercontent.com/36459510/37312214-24970ba2-2618-11e8-9bf7-28982d51ada9.png)
 
En la búsqueda, para la distancia se muestra en unidades megapársec (Mpc). Para su conversión a años luz se debe tener en cuenta que:
1 pársec = 206265 ua = 3,2616 años luz = 3,0857 × 1016 m 
Por tanto para la conversión de Mpc a años luz, por cada Mpc se debe multiplicar por ≈3,262e+6 o 3,26 millones

**Comment by andres-linares** [comment]
¿La distancia no es que podemos obtenerla a partir del valor de RedShift?

Para la solución que ud da, ¿existe alguna manera de implementarlo con la búsqueda mediante script de simbad?

**Comment by andres-linares** [comment]
Por ejemplo:
## Para el objeto NGC 7:
z = 0.005033 (redshift)
distancia  = 21.249325958417209392 mpc (usando calculadoras en internet)
distancia = 18.8, 19.5, 23 mpc (datos de simbad)
distancia = 20.486 mpc (usando base de datos NED)
## Para el objeto NGC 2:
z = 0.025004
distancia = 105.55218150821836787 (usando calculadoras en internet)
distancia = 88.31, 103.2,  102.05 (datos de simbad)
distancia = 94.829 (base de datos NED)
## para el objeto NGC 1500:
z = 0.034287
distancia = 144.76561092944780285 (usando calculadoras en internet)
distancia = 115.88 (datos de simbad)
distancia = 150.333 (base de datos NED)
## para el objeto NGC 3972:
z = 0.002799
distancia = 11.817377994277592279 (usando calculadoras en internet)
distancia = 20.0, 18.0, 20.42, 22.0, 18.0, 18.54, 14.90, 19.8 (datos en simbad)
distancia = 19.404 (base de datos NED)
## Calculadoras:
[RedShift a Kilometros](https://www.convert-me.com/en/convert/length/auredshift.html?u=auredshift&v=0.002799)
[Kilometros a MPC](https://www.google.com.co/search?q=kilometros+a+mpc&oq=kilometros+a+mpc&aqs=chrome..69i57.3683j0j7&sourceid=chrome&ie=UTF-8)
## Base de datos NED (NASA/IPAC EXTRAGALACTIC DATABASE):
[NED](http://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=ngc+3972&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES)

**Comment by jmencisom** [comment]
docs.astropy.org/en/latest/api/astropy.coordinates.Distance.html

**Comment by andres-linares** [comment]
@LinaMejia  por favor revisar el enlace

**Comment by mejiajhonathan** [comment]
`from astropy.cosmology import WMAP9`
`WMAP9.comoving_distance(0.01679)`

El método comoving_distance recibe como parámetro el redshift del objeto de la búsqueda. Toca investigar con alguien que tenga conocimientos en astronomía para decidir cual es la mejor opción respecto a los WMAP, ya que existe el WMAP5, WMAP7 y WMAP9. Ya que hay desconocimiento en esa tipo de medición.
