### ISSUE TITLE
Viabilizar estrategia para generar contenido artículo

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#45]
En el siguiente artículo se presenta un enfoque para producir la tabla de contenido del artículo.

http://www.aclweb.org/anthology/R13-1033

Identificar viabilidad de este enfoque para los artículos NGG. Es viable o no?

Gracias.

**Comment by jmencisom** [comment]
En el siguiente enlace se encuentran todos los artículos científicos asociados a un objeto (Ej. NGC 1):

http://simbad.u-strasbg.fr/simbad/sim-id-refs?Ident=NGC%201&Name=NGC%201

El sigiente paso será extrer de cada artículo científico todas las frases donde se mencione "NGC 1".

Luego aplicar el algoritmo de generación de TOC o alternativamente se podría aplicar un algoritmo de Clustering para agrupar las oraciones por título (Categoría).

**Comment by hamiltonsalazar** [comment]
@danielmrno esta tarea fue asignada el 11 de marzo, no hay ningún reporte de trabajo ni de avance, ¿sucede algo? tampoco se presenta ningún avance en las otras tareas asignadas, se ingresa esta en progreso por prioridad y por favor debe ser resulta esta semana, mostrar avance para el día jueves.

**Comment by hamiltonsalazar** [comment]
@andreveca como líder de equipo por favor me comunica si el integrante de su equipo le ha notificado alguna novedad del por qué no se presenta algún avance en las tareas.

**Comment by hamiltonsalazar** [comment]
Se cierra por tiempo y no se presenta reporte.
