### ISSUE TITLE
Elaborar diagrama Burn down

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#46]
Por favor elaborar diagrama Burn down:

https://en.wikipedia.org/wiki/Burn_down_chart

Considerar esta vesión:

https://en.wikipedia.org/wiki/Burn_down_chart#/media/File:Burn_down_chart.png

Gracias.

**Comment by hamiltonsalazar** [comment]
Se termina el diagrama de Burn down hasta la fecha actual y se presentará en la revisión de avance, además se publicará en una Wiki. 
![captura](https://user-images.githubusercontent.com/36459473/38703636-67133014-3e69-11e8-857d-4963db3a2c7a.PNG)
