### ISSUE TITLE
Ajustar salida script

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#48]
Por favor ajustar la plantilla como se indica:

* mover la etiqueta {{Sky...}} al inicio del artículo. Ejemplo:

{{Sky|02|38|11.565||-01|19|07.02|999}}

{{Infobox galaxy
...

* agregar explícitamente las siguientes secciones:

==See also==
* Página padre

==External links==
* Enlaces externos

== References ==
{{reflist}}

* Agregar las etiquetas

{{Commonscat}}
{{Galaxy}}
{{Ngc15}} --> según corresponda con el ID del objeto NGC

Usar https://en.wikipedia.org/wiki/NGC_1015 como guía.

Gracias!

**Comment by luiscarlosmartg** [comment]
ingeniero @jmencisom  ya solo falta las etiquetas pero no entiendo ¿que son exactamente?

**Comment by jmencisom** [comment]
Solo debe agregar el texto {{Commonscat}} (en todos los casos) y {{Galaxy}} (solo para los objetos de tipo galaxia) a la salida del script. Además, dependiendo del identificador de objecto NGC debe agregar el texto {{Ngc5}} (si está creando la página de NGC 1 hasta NGC 500), o {{Ngc10}} (si está creando la página de NGC 501 hasta NGC 1000), etc.

**Comment by luiscarlosmartg** [comment]
se termino la salida del script, para pronta revisión y cerrar la tarea
