### ISSUE TITLE
Obtener lista que contenga los tipos de objetos astronómicos que existen en wikipedia y dejar el contenido en la Wiki.

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#5]
Según el objeto astronómico, será necesario utilizar una u otra plantilla al momento de generar el **WikiTexto**. Es necesario conocer que objetos astronómicos maneja wikipedia y sus correspondientes plantillas.

**Comment by mejiajhonathan** [comment]
Terminado!!!. En la wiki deje una pagina con el listado de los tipos de objetos astronómicos de WIKIPEDIA.
