### ISSUE TITLE
Reportar tareas artículo científico

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#52]
Por favor reportar las tareas asociadas al artículo científico, por ejemplo:

Suponiendo que debe escribir 50 palabras cada días, las siguientes tareas deberían ser reportadas y resueltas a diario:

Completar 50 palabaras del artículo científico
Completar 100 palabaras del artículo científico
Completar 150 palabaras del artículo científico
...
Completar 2900 palabaras del artículo científico
Completar 2950 palabaras del artículo científico
Completar 3000 palabaras del artículo científico

Con cada avance, verificar la originalidad del texto: https://smallseotools.com/plagiarism-checker/

Muchas gracias.

**Comment by hamiltonsalazar** [comment]
Como lo indiqué en la issue #59 se cambia el plan de trabajo y es a cargo de @luiscarlosmartg el nuevo se encuentra en la issue #147
