### ISSUE TITLE
Asignar responsable artículo informativo

### ISSUE THREAD

**Issue by jmencisom** [jmencisom/wikastro#53]
Por favor asignar un responsable para escribir el artículo informativo que será enviado a https://www.capjournal.org/

Tener en cuenta: 
* guías para someter artículos: https://www.capjournal.org/submission.php
* criterios de revisión: https://www.capjournal.org/peerreview.php
* ejemplos de publicaciones: https://www.capjournal.org/issues/index.php

Las siguientes personas NO pueden ser responsables del artículo informativo (ya tienen partición en el artículo científico): Andrés Linares, Hámilton Salazar, Daniel Moreno.

Gracias

**Comment by hamiltonsalazar** [comment]
Esta labor se presenta un cambio y queda a cargo @danielmrno
