### ISSUE TITLE
Completar 300 palabras del articulo científico 

### ISSUE THREAD

**Issue by danielmrno** [jmencisom/wikastro#59]
Realizar la construcción total del artículo.

**Comment by hamiltonsalazar** [comment]
@danielmrno esta tarea es muy general, por favor indicarme el estimado de palabras por día y la fecha de inicio de construcción de éste, para manejarlo de una manera más detallada en diferentes tareas que le asignaré.

**Comment by hamiltonsalazar** [comment]
@danielmrno hace más de 10 días en esta y otra tarea le pedí el reporte de la cantidad por día, aún no lo he recibido. 
La tarea y en general todo lo correspondiente al articulo queda a cargo de @luiscarlosmartg  partir del momento.

**Comment by hamiltonsalazar** [comment]
@luiscarlosmartg se creará un plan de trabajo nuevo, el cual le asignaré en las unas issues, se tomarán las 300 palabras de base y dividirá en las semanas restantes. Por favor iniciar con base en la issue #27 informarse todo lo necesario acerca del artículo y evento, para iniciar a redactar. Tomaré como semana inicial ésta que culmina, así que estas dos serán las de trabajo más fuerte, ya que deberá aprender a manejar a la herramienta, según las orientaciones del ingeniero @jmencisom el día jueves e iniciar a redactar para alinearse al plan de trabajo.
