### ISSUE TITLE
Obtener lista que contenga todos los tipos de objetos que se encuentran en el NGC (galaxias, estrellas, etc) y dejarlo en la Wiki.

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#6]
Al buscar en _simbad_ los objetos astronómicos que hacen parte del **NGC**, en la información básica -> tipo de objeto aparecen distintas categorías que son necesarias conocerlas.

**Comment by mejiajhonathan** [comment]
Terminado!!!. En la wiki deje una pagina con el listado de los Tipos de Objetos de SIMBAD.
