### ISSUE TITLE
Terminar primera fase de desarrollo

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#60]
Elementos que faltan para terminar la primer fase de desarrollo:

Caption del objeto NGC. (en proceso, límite 8 de abril)
Constelación del objeto NGC. (en proceso)
Distancia en años luz del objeto NGC. (¿?)
Ajustar salida del script. (¿?)

La parte de asignar a un objeto ngc un wikibox específico aún no ha sido reportada por parte del equipo de análisis.

La segunda fase estará compuesta por el código funcionando en un servidor y por la extracción de texto.
Supongo la parte del servidor no nos costará mayor tiempo... La extracción del texto es el punto clave y se requerirá un fuerte apoyo por parte del equipo de análisis (que para esta fase puede tener miembros adicionales, [es solo un consejo] )

**Comment by LinaMejia** [comment]
Distancia en años luz  ya la considero terminada, haría que hacerle algo más @andres-linares

**Comment by hamiltonsalazar** [comment]
@andreveca tener en cuenta la solicitud de @andres-linares  y reitero lo ya dicho anteriormente con cada uno por interno, si alguno de los dos requiere apoyo en un momento me comunican y gestionamos personal del grupo de pruebas, según su carga laboral. 

Anexar a la segunda fase el diseño, comunicación y creación del modelo de la página web.
