### ISSUE TITLE
Elaborar Mockup de la página web de inicio.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#67]
Realizar el diseño y mostrarlo a través de un Mockup de la página web de inicio, para la reunión del próximo 18 de abril.

**Comment by hamiltonsalazar** [comment]
Por favor presentar informes del progreso de éste diseño y contar con el aval del líder de equipo @andres-linares para llevarlo a la sesión.

**Comment by hamiltonsalazar** [comment]
@luiscarlosmartg  por favor generar un reporte en comentarios a esta issue, con imágenes adjuntas del mockup terminado y con los aportes que se le realizaron a éste en clase. 
Culminar esta e iniciar la siguiente labor #68 y juntas sean la base para la issue #69

**Comment by hamiltonsalazar** [comment]
@luiscarlosmartg por favor generar el reporte acá correspondiente a ambas, con imágenes, para poder cerrar ambas.

**Comment by luiscarlosmartg** [comment]
no se pueden insertar imagenes, ¿
las subo a un drive?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-04-24 16:28 GMT-05:00 Smith Carvajal <notifications@github.com>:

**Comment by hamiltonsalazar** [comment]
Se hizo la labor, nunca se presentaron reportes.
