### ISSUE TITLE
Elaborar Mockup de la página web cuando se muestra el código para pegar en Wikipedia.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#68]
El Mockup será intuitivo, éste indicara cuando será la de copia del texto que aparece y posteriormente pegarlo en WIKIPEDIA.

**Comment by luiscarlosmartg** [comment]
@hamiltonsalazar  esta ya se puede cerrar

**Comment by hamiltonsalazar** [comment]
@luiscarlosmartg es necesario presentar las evidencias en los comentarios de esta issue o en la #69

**Comment by hamiltonsalazar** [comment]
Se hizo la labor, nunca se presentaron reportes.
