### ISSUE TITLE
Reemplazar la manera en la cual se concatena el texto

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#7]
## El problema
En la siguiente imagen se puede observar como la concatenación en una linea impide que se cumpla el estándar de codificación:
![image](https://user-images.githubusercontent.com/15129146/36456296-360ea6c0-1672-11e8-98dc-6814312d3e46.png)

**Recientemente he encontrado artículos donde explican que la concatenación mediante el '+' es ineficiente y peligrosa en algunos proyectos.** Por ello ha de buscarse una manera de concatenar diferente al '+' y que además cumpla el estándar de codificación donde las líneas no pueden tener más de 80 caracteres.

## Actualizar estándar de codificación
El estándar de codificación se basó en el supuesto de la concatenación mediante '+' y el uso de múltiples lineas. Al observarse que esto no es aceptado por python, es necesario modificar la parte siguiente con su respectivo ejemplo:

> En casos donde se requiera concatenar una gran cadena de texto, entonces el signo de concatenar (+) deberá ser el último de la linea y continuar en la linea con una doble tabulación.

**Comment by hamiltonsalazar** [comment]
Debido a la ausencia (por incapacidad médica) de @LinaMejia la tarea no puede continuar en progreso, hasta que la compañera se reporte en capacidades de culminarla o pueda ser asignada a algún otro miembro del equipo.

**Comment by andres-linares** [comment]
Acabo de probar el método que dijo Lina (format).
En el último commit se puede observar que se hace uso de format para concatenar variables con texto. Por favor revisar si es de acuerdo a lo que investigo o hay algún inconveniente.

tiempo de trabajo: 0.6 horas

**Comment by LinaMejia** [comment]
Mientras investigaba encontré que la función más optima para concatenar cadenas es f-strings pero no fue propuesta como solución ya que esta está disponible a partir de la versión 3.6 de python, la función join fue descartada ya que es para concatenar arreglos de Strings que utilicen el mismo separado, por último propongo como solución la función format y modifico el estándar de codificación indicando cuando y un ejemplo de como usarla. Linares implementó la función en el código.
