### ISSUE TITLE
Desarrollar algoritmo para probar la obtención de información de los 7840 objetos NGC (pruebas)

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#8]
## Dudas
- ¿Cuantos objetos NGC (de los 7840) existen en la base de datos simbad?

Deberá ser desarrollado un algoritmo que cuenta el número de objetos existentes en la base de datos de simbad.

El algoritmo utilizado deberá ser subido al repositorio en una nueva rama llamada **"Test_1"**

**Comment by jmencisom** [comment]
Esta tarea tiene un alcance muy amplio debería dividirse en tareas más pequeñas (aprox. 4-8h de esfuerzo en cada tarea).

**Comment by mejiajhonathan** [comment]
Necesito de la ayuda de @georgebaron y/o @LinaMejia, el dia de ayer hice unas pruebas y funcionaron, pero el dia de hoy al encender mi pc, me encuentro con que este tiene un problema y no enciende. Así que mientras le encuentro la solución a éste, necesito de su colaboración. Yo les puedo ayudar con el algoritmo desde sus máquinas. @hamiltonsalazar

**Comment by hamiltonsalazar** [comment]
@georgebaron por favor comunicarse inmediatamente con @mejiajhonathan para que empalmen el avance de la tarea y pueda continuar con ella o ayudar en lo que requiera el compañero, debido a que se encuentra sin equipo, usted acaba de terminar la anterior tarea y Lina sigue con incapacidad.

**Comment by andres-linares** [comment]
Corriendo el algoritmo...
![image](https://user-images.githubusercontent.com/15129146/37184273-7aab55b0-2308-11e8-8c03-bfc9aa9522f0.png)
Los "buenos" son los que existen en la base de datos y los "malos" son los que no existen 👍

**Comment by andres-linares** [comment]
El algoritmo lo subí a pruebasObjetos. Por favor prueben el código desde sus equipos y reportan los resultados.
El algoritmo evalúa hasta el objeto 10.000

**Comment by andres-linares** [comment]
Se analizaron los primeros 7.565 objetos NGC contra la base de datos **simbad**.

## Resultados:

No se encontraron 374 de 7838.
Se encontraron 7464 de 7838.
Objetos no encontrados: [6, 18, 21, 30, 32, 33, 82, 122, 123, 156, 158, 211, 302, 310, 313, 316, 343, 370, 372, 377, 387, 400, 401, 402, 405, 421, 453, 506, 510, 537, 552, 553, 607, 610, 616, 618, 629, 635, 728, 730, 737, 757, 764, 771, 793, 866, 901, 952, 1014, 1040, 1059, 1113, 1146, 1147, 1170, 1173, 1176, 1178, 1183, 1197, 1235, 1237, 1240, 1243, 1251, 1276, 1378, 1408, 1420, 1429, 1443, 1458, 1475, 1479, 1480, 1523, 1524, 1525, 1619, 1639, 1655, 1674, 1675, 1707, 1742, 1757, 1884, 1908, 1927, 1988, 2052, 2054, 2142, 2167, 2189, 2198, 2218, 2226, 2277, 2278, 2279, 2284, 2285, 2299, 2317, 2334, 2356, 2361, 2386, 2390, 2399, 2400, 2404, 2412, 2436, 2464, 2465, 2471, 2478, 2515, 2520, 2542, 2568, 2589, 2605, 2653, 2696, 2700, 2702, 2703, 2705, 2707, 2741, 2757, 2760, 2837, 2846, 2847, 2871, 2879, 2886, 2901, 2932, 2995, 2999, 3000, 3004, 3046, 3063, 3097, 3123, 3129, 3167, 3170, 3176, 3181, 3217, 3284, 3291, 3295, 3317, 3328, 3342, 3345, 3382, 3388, 3401, 3460, 3461, 3472, 3480, 3484, 3494, 3498, 3505, 3538, 3548, 3560, 3575, 3578, 3685, 3698, 3708, 3709, 3747, 3792, 3797, 3852, 3874, 3889, 3927, 3939, 3948, 3965, 4099, 4107, 4130, 4153, 4154, 4160, 4209, 4280, 4315, 4317, 4327, 4347, 4367, 4368, 4381, 4398, 4508, 4530, 4554, 4582, 4610, 4667, 4752, 4768, 4769, 4805, 4817, 4844, 4847, 4913, 4937, 4962, 4982, 5067, 5106, 5160, 5200, 5242, 5268, 5299, 5309, 5388, 5404, 5428, 5429, 5432, 5435, 5465, 5467, 5502, 5558, 5565, 5578, 5586, 5609, 5621, 5651, 5655, 5699, 5703, 5808, 5816, 5834, 5856, 5867, 5871, 5877, 5884, 5901, 5922, 5948, 6046, 6049, 6059, 6082, 6133, 6170, 6191, 6227, 6294, 6298, 6344, 6354, 6410, 6413, 6428, 6431, 6437, 6448, 6450, 6455, 6480, 6498, 6499, 6506, 6519, 6533, 6551, 6556, 6564, 6600, 6610, 6648, 6655, 6659, 6666, 6668, 6678, 6682, 6693, 6714, 6731, 6748, 6767, 6777, 6785, 6795, 6815, 6859, 6892, 6896, 6933, 6953, 6966, 6973, 6980, 7005, 7028, 7045, 7050, 7054, 7088, 7105, 7122, 7136, 7143, 7150, 7161, 7186, 7210, 7238, 7295, 7327, 7333, 7338, 7350, 7403, 7453, 7459, 7471, 7477, 7493, 7502, 7504, 7520, 7526, 7555, 7560, 7561, 7565, 7571, 7574, 7575, 7581, 7605, 7607, 7614, 7627, 7639, 7666, 7668, 7669, 7670, 7748, 7763, 7791, 7804, 7815, 7830, 7833]


A partir del objeto 7838 no se encuentran más objetos...

**Comment by andres-linares** [comment]
Pendiente de revisión por el líder

**Comment by andres-linares** [comment]
180 consultas por minuto

**Comment by hamiltonsalazar** [comment]
@georgebaron líder del equipo de calidad, se requiere su punto de vista para dar por terminada la tarea. Recordemos que como líderes de equipo seremos los encargados de cerrar las tareas correspondientes a su propio equipo, también lo podremos hacer yo como Gerente, el ingeniero o @fraroca97 como administrador, si se considera pertinente. Sin embargo, debemos estar realizando control sobre las tareas del respectivo equipo y acá se solicita la revisión del líder para darla por cerrarla @georgebaron
