### ISSUE TITLE
Determinar las revistas que permiten acceder a los artículos

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#83]
## Problema
Antes de acceder a los documentos pdf (que son las referencias bibliográficas) debo entender como funcionan las páginas web de las revistas y de tal manera acceder al enlace de descarga. Ya he hecho un poco de investigación y he obtenido las siguientes cláusulas:
![imagen](https://user-images.githubusercontent.com/15129146/38643847-280c2134-3da4-11e8-9320-4b049e35a1a0.png)
y
![imagen](https://user-images.githubusercontent.com/15129146/38643860-369a86aa-3da4-11e8-921d-18cec1375fd3.png)

En la primer imágen está una descripción de forma general y la segunda es una descripción más orientada a la solución algorítmica.
El trabajo de este issue será determinar la veracidad de las cláusulas. En caso de que la información que haya puesta sea incorrecta o deba modificarse, responder en este issue. De igual manera si existe una nueva url que no haya visto antes la pueden reportar. Si existe nueva información, también reportarla.

## Explicación
Para usar el algoritmo deben hacer lo siguiente:
- Abrir la consola (o terminal) y ejecutar el entorno virtual (o crear un nuevo entorno virtual y volver a clonar el repositorio para no lidiar con tantas librerías, **es más aconsejable crear desde cero**)
- Ubicarse en el repositorio.
- Escribir el comando **git fetch** para obtener las últimas actualizaciones
- Escribir el comando **git checkout text_extraction** para cambiar de rama
- Escribir el comando **pip install -r requirements.txt** para instalar las librerias
- Escribir el comando **jupyter notebook** para ejecutar el entorno web de jupyter
- Dirigirse a la carpeta **src**
- Dirigirse a la carpeta **text_extraction_test**
- Abrir el archivo **Extracción de texto.ipynb**
- Escoger un número aleatorio entre 1 y 7800 y escribirlo en la siguiente ubicación:
![imagen](https://user-images.githubusercontent.com/15129146/38644214-650513e2-3da5-11e8-9783-9e46fca8c9ac.png)
- Oprimir el boton de reiniciar:
![imagen](https://user-images.githubusercontent.com/15129146/38644231-77640278-3da5-11e8-8580-644d37c66b7b.png)
- Esperar hasta que se recolecte toda la información
- Una vez obtenida la infomación, ir abriendo los distintos enlaces y verificar la veracidad de las cláusulas.

**Comment by andreveca** [comment]
Mi computador se dañó (Estoy tratando de arreglarlo) por tanto no he podido avanzar en esta tarea.
@hamiltonsalazar  que podría hacer al respecto para no atrasar al equipo de desarrollo?

**Comment by hamiltonsalazar** [comment]
Somos dos personas sin equipo señorita @andreveca. Por ahora apoyarse con los miembros de su equipo, recuerde que como se ha liberado a @danielmrno del artículo científico que era el que requería prioridad en el momento su carga de equipo puede aumentar, además cuenta con @mejiajhonathan también para apoyarse en él. 

Sin embargo durante el fin de semana le sugiero las tareas que sean sólo de investigación, si puede adelantar desde su celular, se comunique con otro miembro para que este le pueda plasmar sus ideas, durante el transcurso de la semana podríamos gestionar un equipo de la sala donde nos reunimos para que lo use en su tiempo libre con apoyo del ingeniero @jmencisom

**Comment by hamiltonsalazar** [comment]
@andreveca por favor asignar esta labor a un miembro de su equipo ya que requiere de prioridad.

**Comment by andreveca** [comment]
@danielmrno Por favor realizar esta tarea

**Comment by hamiltonsalazar** [comment]
@danielmrno ¿tenemos algún avance de ello?

@andreveca ¿se ha presentado algún avance o comunicación del progreso de esta labor?

**Comment by andreveca** [comment]
El día Lunes le preguntándole si la había visto (la asignación de la tarea), respondiéndome que sí, sin embargo no menciono nada más al respecto

**Comment by andreveca** [comment]
@danielmrno como va con la tarea?  Recuerde que @hamiltonsalazar le pidió esta tarea para el día de ayer y no he visto reporte al respecto además, que es requerida con urgencia por el equipo de desarrollo

**Comment by andreveca** [comment]
@danielmrno la tarea lleva retrasada la entrega más de una semana y es NECESARIA INMEDIATAMENTE la entrega de esta.

@hamiltonsalazar que hacemos al respecto? no ha reportado nada

**Comment by hamiltonsalazar** [comment]
El ingeniero @jmencisom ya tiene el reporte de ésta y demás labores sin terminar y que generan retardo a otros miembros o equipos. Estamos a la espera de una medida de su parte.

**Comment by andreveca** [comment]
Como @danielmrno no ha realizado ningún reporte y es necesario avanzar con las tareas, se opta por reasignar esta a @mejiajhonathan como sugerencia del Ingeniero @jmencisom

**Comment by mejiajhonathan** [comment]
Para extraer los pdfs de las revistas, se tomaron aquellas que tiene acceso libre y/o gratuito a los PDFs:
[SAO/NASA Astrophysics Data System (ADS)](adsabs.harvard.edu)
[Astronomy and Astrophysics Supplement Series (aas)](aas.aanda.org)
[Academic.oup (Oxford Academic)](academic.oup.com)
[Aanda.org](www.aanda.org)
[IOPscience](iopscience.iop.org)

**Comment by andreveca** [comment]
Se da por culminada ya que da respuesta a la solicitado por el equipo de desarrollo
