### ISSUE TITLE
Realizar revision de las relaciones de SIMBAD con wikipedia. 

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#84]
Asignar la columna extra y definirla a propio criterio y decisión, para lograr el trabajo más optimo de éstos datos en el área de desarrollo.  #33 
Editar y modificar la wiki correspondiente a los resultados.

**Comment by mejiajhonathan** [comment]
Se hizo la actualización correspondiente en la wiki "Relación tipos de objetos SIMBAD con plantillas de Wikipedia" con un enlace llamdao "Actualizacion Template". Algunos objetos se dejaron para consultar con el ingeniero, ya que por criterio, no tienen ninguna relación con las plantillas previamente definidas.
