### ISSUE TITLE
Elegir revista para publicar artículo divulgativo.   

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#85]
Realizar una búsqueda de otras opciones de revistas científicas físicas u online, donde podamos enviar el artículo que se encuentra desarrollando @luiscarlosmartg. 

Se sugiere buscar diferentes opciones y tener en cuenta la base de datos de Colciencias "publindex".

Para revistas nacionales indexadas: http://scienti.colciencias.gov.co:8084/publindex/EnIbnPublindex/buscador.do

Para revistas internacionales homologación: http://scienti.colciencias.gov.co:8084/publindex/jsp/EnRevistaHM/search.jsp

Tener diferentes posibilidades entre nacionales e internacionales y preferiblemente elegir la mejor de ellos.

**Comment by andreveca** [comment]
**INTERNACIONAL**
Nombre: Journal of astronomy and space science
ISSN: 2093-5587
Clasificación : B
Fechas de publicación:  Trimestral (Marzo, Junio, Septiembre, Diciembre)

Nombre: Journal of information processing systems
ISSN: 1976-913X
Clasificación : B
Fechas de publicación:  Ultimo día de (Febrero, abril, junio, agosto, octubre y diciembre)

Nombre: Journal of the korean astronomical society
ISSN: 1225-4614
Clasificación : A2
Fechas de publicación: Febrero 28, Abril 30, Junio 30, Agosto 31, Octubre 31 y Diciembre 31.




              **NACIONAL**
Nombre : Ciencia e Ingeniería Neogranadina 
ISSN: 0124-8170
Clasificación : B
Fechas de publicación: Semestral

Nombre : Revista facultad de ingeniería Universidad de Antioquia
ISSN: 0120-6230
Clasificación : B
Fechas de publicación: Marzo, junio, septiembre y diciembre

Nombre : Revista ingenierías Universidad de Medellín
ISSN: 1692-3324
Clasificación : B
Fechas de publicación:  Enero-Julio -> Cierre: septiembre 30
                                      Julio-Diciembre -> Cierre: Marzo 31

Nombre : Revista Logos Ciencia & Tecnología
ISSN: 2145-549X
Clasificación : B
Fechas de publicación:  Trimestral (Enero-Marzo; Abril-Junio; Julio-Septiembre; Octubre-Diciembre)

Nombre : REVISTA VIRTUAL UNIVERSIDAD CATÓLICA DEL NORTE
ISSN: 0124-5821
Clasificación : B
Fechas de publicación: Frebrero-Mayo; Mayo-Agosto; Septiembre-Diciembre

**Comment by hamiltonsalazar** [comment]
@jmencisom ingeniero por favor nos podría dar el link de la página que nos recomendó en clase para saber si las revistas se encuentran en los cuartiles y así proceder a hacer la elección de la revista a publicar. 
@danielmrno por favor ir adelantándose por ahora y revisar la revista "Journal of the korean astronomical society" que cuenta con clasificación A2, si exige algún formato en especifico de escritura, por ahora será nuestra primera opción a publicar.

**Comment by jmencisom** [comment]
http://www.scimagojr.com/journalrank.php

**Comment by andreveca** [comment]
@hamiltonsalazar con la página que dio el ingeniero que tendría que hacer?

**Comment by andreveca** [comment]
Esto es lo que aparece de la revista seleccionada:
![image](https://user-images.githubusercontent.com/36459536/39412026-2406e7d2-4bdb-11e8-8817-0003871cb51e.png)

Pero no sé que hacer con dicha información, agradecería colaboración @hamiltonsalazar

**Comment by andreveca** [comment]
@hamiltonsalazar dejamos la tarea sin terminar hasta hablar con el ingeniero?

**Comment by hamiltonsalazar** [comment]
Si señora, hasta la próxima clase que podamos reunirnos con él y decidir en conjunto.

**Comment by jmencisom** [comment]
La revista http://jips-k.org/ es una revista especializada, por lo tanto el escrito debería ser un artículo científico (en lugar de un artículo orientado al público en general). Sin embargo, recuerden que ya estamos trabajando en el artículo científico para la conferencia de Bélgica.

Debemos seguir con la búsqueda de revistar no especializadas o escribir otro artículo científico (con un enfoque distinto al del artículo de la conferencia)

**Comment by andreveca** [comment]
Encontre estas @hamiltonsalazar para verificar que cumpla con lo que dice el ingeniero o ya seria optar por una revista Nacional 

JOURNAL OF INFORMATION TECHNOLOGY - 0268-3962 - http://www.guide2research.com/journal/journal-of-information-technology

Information Systems - 0306-4379 https://www.journals.elsevier.com/information-systems/

INFORMATION SYSTEMS RESEARCH - 1047-7047 http://www.guide2research.com/journal/information-systems-research

**Comment by hamiltonsalazar** [comment]
https://www.capjournal.org por medidas de tiempo usaremos la primer opción, debido a que las demás son revistas científicas.
