### ISSUE TITLE
Obtener el descubridor de un objeto NGC y la fecha en que lo descubrió.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#86]
Existe una página web que da información sobre la primera persona que descubrió el objeto NGC, la fecha en la que lo hizo, y el lugar en el que fue observado.

**Comment by andres-linares** [comment]
La página es la siguiente:
https://cseligman.com/text/atlas/ngc0.htm
Por favor revisar la página y si servirá para algo más.

**Comment by andreveca** [comment]
Respecto a la fecha es necesario el día y mes del mismo? 
En una de las paginas que referencia la página que comento Andres hay un archivo de excel de información sobre los diferentes objetos NGC sin embargo, en la hoja solo esta el año y nombre del descubridor. Ademas, hay una columna sobre la constelación cosa que no sé si les facilite el trabajo a los de desarrollo

**Comment by hamiltonsalazar** [comment]
@andreveca por ahora podríamos usar solo el año, mientras encontramos una fuente que nos brinde toda la fecha completa.

Podría por favor compartir el contenido encontrado para que sea examinado y trabajado.

**Comment by andreveca** [comment]
@hamiltonsalazar En el enlace que da Andres la dan, solo que esta en un párrafo por eso preguntaba si era necesario completa, sin embargo cuando muestre los resultados colocare ambas

**Comment by andreveca** [comment]
Después de haber realizado la respectiva investigación a la pagina comentada por @andres-linares me pude dar cuenta que esta busca en otras páginas, las cuales referencia en la misma por tanto, me dispuse a buscar en dichas páginas si podría haber información más detallada al respecto, encontrando lo siguiente:

Página: http://www.astronomy-mall.com/Adventures.In.Deep.Space/NGC%20complete.htm
![screenshot_1](https://user-images.githubusercontent.com/36459536/39339147-c13623ca-498c-11e8-8184-c7e09bab3f79.png)

En dicha página se puede visualizar todos los objetos NGC desde 1-7840 (o en grupos de 999), los cuales están separados por una linea de *************... en donde se puede encontrar la información requerida en el ultimo párrafo de cada objeto, es decir, el descubridor y la fecha correspondiente (Año, mes, día) . Por otro lado encontré en dos páginas, en las cuales se pueden descargar dos archivos de excel con información correspondiente a los objetos, por un lado esta:

Página: http://ngcicproject.org/public_HCNGC/HCNGC.htm
![image](https://user-images.githubusercontent.com/36459536/39341351-69a6b78a-4998-11e8-987d-b2eaa13748fd.png)
 En donde se puede encontrar diferente información respecto a los objetos, más concretamente, dos columnas para el año y descubridor respectivamente.
Para más información sobre las columnas en la siguiente página esta la documentación respectiva: http://ngcicproject.org/public_HCNGC/The_HCNGC_intro.pdf


Página: http://www.klima-luft.de/steinicke/ngcic/ngcic_e.htm
![image](https://user-images.githubusercontent.com/36459536/39341738-28215ebc-499a-11e8-8908-4ac5355f4ea5.png)

En esta también se puede encontrar información respectiva a los objetos,sin embargo, no hay información respecto al descubridor. Donde las especificación de las columnas es la siguiente:
![image](https://user-images.githubusercontent.com/36459536/39341811-846b0be6-499a-11e8-99bc-679e0a1896d6.png)

Finalmente, a manera de comentario, encontré una Base de datos extragalactica de la NASA, llamada NAV donde tiene las siguientes opciones, 

Página: http://ned.ipac.caltech.edu/
![image](https://user-images.githubusercontent.com/36459536/39342058-bf731dea-499b-11e8-8449-f22f283af3b8.png)

Sin embargo no indague mucho sobre ella por tanto no sé si será de utilidad al proyecto, dejo la duda por si desean que busque información al respecto

Quedo al tanto cualquier cosa ^^ Finalmente, si algunos de los Excel les es de utilidad comentarme y les indico donde descargarlos o enviarselos.

**Comment by hamiltonsalazar** [comment]
@andres-linares ¿algo más que agregar?

**Comment by hamiltonsalazar** [comment]
Ok la tarea se da por culminado, lo siguiente es trabajo de desarrollo @LinaMejia  💪💪
