### ISSUE TITLE
Identificar la posibilidad de extraer información a partir de la bibliografía relacionada a un objeto NGC en SIMBAD. Parte 1

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#87]
Consultar si la bibliografía que se encuentra en SIMBAD y está relacionada con un objeto, es totalmente respecto al objeto para así extraer ésta información.

**Comment by andres-linares** [comment]
Siguiendo los pasos explicados en el issue #83, es posible resolver este issue.

**Comment by andreveca** [comment]
@danielmrno  Ya que el issue #83 es usted el responsable, continúe con esta tarea, además que se espera el informe de la solución de las anteriores y ésta para el día Miércoles.

**Comment by andreveca** [comment]
@danielmrno No veo ningún avance de las tareas, como va con eso?

**Comment by andreveca** [comment]
Ya que @danielmrno no ha realizado un reporte hasta el momento respecto a esta tarea, se opta por reasignarla ya que esta es requerida por otras tareas, ergo yo seguiré con el desarrollo de esta.

**Comment by hamiltonsalazar** [comment]
@andreveca debido a que esta labor está enlazada a la issue #83 lo mejor es que continúe con ésta @mejiajhonathan y por favor usted avanzar en otra diferente.

**Comment by mejiajhonathan** [comment]
Según la tabla de referencias dentro de la página de SIMBAD, un articulo puede hacer referencia a uno o varios objetos que estén dentro de su base de datos, esta información fue verificada tomando los artículos de manera aleatoria asociados a las referencias bibliográficas de los objetos NGC.

Una vez se verificó esta información, se procedió a buscar cadenas o expresiones asociadas con los objetos NGC dentro de los pdfs, lo que permitió visualizar y dar como resultado, que muchos de los pdfs no hacen referencia de manera directa a los objetos y que gran parte de la información indexada y asociada a un objeto, no tiene la suficiencia necesaria para armar las descripciones para el articulo de wikipedia de ese mismo objeto. 

Por lo cual se hace la sugerencia de extraer la mayor cantidad de información de los artículos sea o no de referencia de ese objeto del cual se extrajo su tabla de referencia e ir almacenándola, de ser necesaria, en una especie de "memoria caché" en caso tal de que la información extraída no sea suficiente para generar párrafos o texto para el articulo de wikipedia.

**Comment by andreveca** [comment]
Se da por culminada la tarea además de haber hecho la sugerencia al equipo de desarrollo respecto a la información extraída ( implementar una especie de "memoria cache" para almacenar información )
