### ISSUE TITLE
Identificar el tipo de información que se extraerá de un objeto y que alimentará el cuerpo principal del artículo. Parte 1

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#89]
Consultar y definir: 

- ¿Qué tipo de información se puede extraer? 

- ¿Identificar los hallazgos científicos sobre el objeto? 

- Otros datos y curiosidades que puedan servir de alimento al artículo.

**Comment by andreveca** [comment]
@mejiajhonathan la tarea ya esta terminada ? Para decirle a @hamiltonsalazar que revise y decidan si se da por cerrada la tarea

**Comment by mejiajhonathan** [comment]
Como es la parte 1, considero que si. Espero la aprobación de @hamiltonsalazar o de @andreveca, y así cerrar este ¨issue¨.
