### ISSUE TITLE
Encontrar una manera sencilla de obtener la información básica de un objeto NGC

### ISSUE THREAD

**Issue by andres-linares** [jmencisom/wikastro#9]
## Problema
Actualmente se usa una técnica de **web scrapping** para obtener la información básica que existe sobre un objeto NGC en simbad. El problema radica en que las distintas páginas de los objetos NGC no cumplen con un mismo formato y, por lo tanto, hacer web scrapping a un contenido tan **cambiante** es una tarea compleja y propensa a errores.
###  _**Manera actual en que funciona:**_
![image](https://user-images.githubusercontent.com/15129146/36606782-b980efb4-1892-11e8-8a48-14d8faadf948.png)
Obtiene todo el documento html y se hace una búsqueda en él.
### _**Ideal:**_
![image](https://user-images.githubusercontent.com/15129146/36606886-05a19ce0-1893-11e8-8665-9aef9fed60f8.png)
Obtener un resultado en el navegador con facilidad al obtener datos.

### _**Ideal 2:**_
![image](https://user-images.githubusercontent.com/15129146/36607244-098fff80-1894-11e8-8fbc-bbba1c812241.png)
Hacer uso de una API para simbad que obtenga los resultados.

## Resultados
Los resultados de la investigación deberán ser expresados en la wiki del repositorio. Cualquiera de los dos ideales puede ser posible.
No hay necesidad de implementar código en el repositorio, solo es necesario el resultado de la investigación para que el equipo de desarrollo escoja una vía de trabajo.

**Comment by andres-linares** [comment]
Esto fue lo que encontré:
![image](https://user-images.githubusercontent.com/15129146/36636375-a1423e74-1993-11e8-963f-9a53100783f6.png)

**Comment by andreveca** [comment]
Hola, respecto a lo que había puesto en el wiki, uno de los ideales que
coloco era respecto a una librería llamada *astroquery *(no sé si miro
respecto a esta) algunos de los métodos que vi en los ejemplos hacían esto
(imagen), ademas hay más métodos que tendría que mirar la información
arrogan incluyendo la moenclatura que usan. No sé que opine al respecto o
si es más optimo el que tenia pensado, cualquier cosa me dice





Paula Velasquez C.
160003342

2018-02-24 18:51 GMT-05:00 Andrés Linares <notifications@github.com>:
