### ISSUE TITLE
Recolectar información sobre las distintas aproximaciones para extraer texto usando Machine Learning. Parte 2

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#93]
Investigar acerca de cuáles son las diferentes técnicas y algoritmos que trabajan con la obtención automatizada de texto y cómo funcionan cada uno de estos.

**Comment by andreveca** [comment]
@hamiltonsalazar Creo que esta tarea se puede dar por terminada, verificar según el criterio de @andres-linares
