### ISSUE TITLE
Mostrar resultados de la investigación sobre la recolección de información.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#94]
Realizar un exposición del tema investigado y tratado en la issue  #93. Requiere terminar con anterioridad la issue #93

**Comment by andreveca** [comment]
Los resultados obtenidos de la investigación de Machine Learning esta en el issue #92 y ya que estamos cortos de tiempo, considero que se puede dar por culminada @hamiltonsalazar por favor revisar
