### ISSUE TITLE
Escoger el método para extraer el texto.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#95]
Investigar y seleccionar el método o métodos más óptimos y apropiados para realizar la extracción del texto.  Generar un reporte inmediato al equipo de desarrollo, para su creación y codificación, preferiblemente mediante una Wiki.

**Comment by mejiajhonathan** [comment]
Se documenta y se muestran pequeños ejemplos sobre el uso de la librería PDFMiner utilizada por el equipo de desarrollo para la extracción de texto de los PDFs en la wiki [Librería Extracción Texto PDF](https://github.com/jmencisom/wikastro/wiki/Libreria-Extraccion-Texto-PDF)

**Comment by andreveca** [comment]
@fraroca97 esta tarea la esta desarrollando usted por tanto, creo conveniente que este asignada a usted. Verificar si se da por culminada o a quien se le debe asignar

**Comment by mejiajhonathan** [comment]
Se da por culminado este issue, @fraroca97 me informa que la parte de la extracción de texto de los pdfs está en la rama ¨text_extraction¨, a la espera de que se fusione en la rama ´´master´´.

**Comment by andreveca** [comment]
Por lo anterior comentado se da por culminada esta tarea
