### ISSUE TITLE
Probar y  analizar los métodos de extracción del texto.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#97]
Realizar las pruebas y el análisis de los métodos codificados y notificados a través de la issue #96  

Para el desarrollo de esta se requiere tener culminada la issue #98 

Si por algún motivo se dictamina negativamente, se reactivará posteriormente a esto las issue #95 y #96. Este proceso no puede repetirse más de una segunda vez y se continuará a la siguiente issue eligiendo a criterio propio la más efectivo de los métodos trabajados.

**Comment by andreveca** [comment]
@fraroca97 revisar esta issue ya que usted trabajando en ello y verificar si se puede dar por culminada
