### ISSUE TITLE
Desarrollar la manera en la cual se probará la efectividad del texto obtenido mediante la implementación de Machine Learning.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#98]
Criterios a tener en cuenta: 

- ¿Qué factores determinan que el texto es bueno?

- Coherencia

- Tamaño

- Similitudes

- Variabilidad

- Probar la efectividad usando un método automatizado o leyendo el texto extraído

Generar un reporte inmediato al equipo de desarrollo, para su creación y codificación, agregarlo al reporte de a la issue #95

**Comment by andres-linares** [comment]
Scikitlearn provee modulos para conocer la clasificación correcta entre las tres categorias:
- abstract.
- observation.
- structure.
